CREATE TABLE ELITE_ROLLOVER (
 ID               INTEGER UNSIGNED NOT NULL,
 YEAR             SMALLINT UNSIGNED NOT NULL,
 LEGS             SMALLINT UNSIGNED NOT NULL,
 DISTANCE         INTEGER UNSIGNED NOT NULL,
 PRIMARY KEY (ID, YEAR),
 FOREIGN KEY (ID) REFERENCES PILOTS(ID) ON UPDATE CASCADE ON DELETE CASCADE
) CHARACTER SET latin1;