CREATE TABLE ELITE_LEVELS (
 NAME                 VARCHAR(32) NOT NULL,
 YR                   SMALLINT UNSIGNED NOT NULL,
 LEGS                 SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 DISTANCE             INTEGER UNSIGNED NOT NULL DEFAULT 0,
 POINTS               INTEGER UNSIGNED NOT NULL DEFAULT 0,
 BONUS                SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 COLOR                INTEGER UNSIGNED NOT NULL DEFAULT 0,
 TARGET_PCT           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 VISIBLE              BOOLEAN NOT NULL DEFAULT TRUE,
 PRIMARY KEY (NAME, YR)
) CHARACTER SET latin1;