CREATE TABLE ELITE_ROLLOVER (
 ID               INTEGER UNSIGNED NOT NULL,
 YEAR             SMALLINT UNSIGNED NOT NULL,
 LEGS             SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 DISTANCE         INTEGER UNSIGNED NOT NULL DEFAULT 0,
 PTS              INTEGER UNSIGNED NOT NULL DEFAULT 0,
 PRIMARY KEY (ID, YEAR),
 FOREIGN KEY (ID) REFERENCES PILOTS(ID) ON UPDATE CASCADE ON DELETE CASCADE
) CHARACTER SET latin1;