CREATE TABLE ELITE_LT_STATUS (
 ID                   INTEGER UNSIGNED NOT NULL,
 ABBR                 VARCHAR(5) NOT NULL,
 CREATED              DATETIME NOT NULL,
 UPD_REASON           TINYINT UNSIGNED NOT NULL DEFAULT 0,
 PRIMARY KEY (ID, ABBR),
 FOREIGN KEY (ABBR) REFERENCES ELITE_LIFETIME(ABBR) ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY (ID) REFERENCES PILOTS(ID) ON UPDATE CASCADE ON DELETE CASCADE
);