CREATE TABLE ELITE_LIFETIME (
 ABBR                VARCHAR(5) NOT NULL,
 NAME                VARCHAR(32) NOT NULL,
 DISTANCE            INTEGER UNSIGNED NOT NULL DEFAULT 0,
 LEGS                INTEGER UNSIGNED NOT NULL DEFAULT 0,
 LEVELNAME           VARCHAR(32) NOT NULL,
 YR                  SMALLINT UNSIGNED NOT NULL,
 PRIMARY KEY (NAME),
 CONSTRAINT UNIQUE (ABBR),
 FOREIGN KEY (LEVELNAME, YR) REFERENCES ELITE_LEVELS (NAME, YR) ON UPDATE CASCADE
);