CREATE TABLE POSITIONS (
 FLIGHT_ID			INTEGER UNSIGNED NOT NULL,
 REPORT_TIME		DATETIME(3) NOT NULL,
 LAT				DECIMAL (9,4) NOT NULL,
 LNG				DECIMAL (9,4) NOT NULL,
 B_ALT				INTEGER NOT NULL,
 HEADING			SMALLINT NOT NULL,
 ASPEED				SMALLINT NOT NULL,
 GSPEED				SMALLINT NOT NULL,
 VSPEED				SMALLINT NOT NULL,
 MACH				DECIMAL (5,3) UNSIGNED NOT NULL,
 FUEL				INTEGER UNSIGNED NOT NULL,
 PHASE				TINYINT NOT NULL NOT NULL,
 FLAGS				INTEGER UNSIGNED NOT NULL DEFAULT 0,
 WIND_HDG			SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 WIND_SPEED			SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 PRIMARY KEY (FLIGHT_ID, REPORT_TIME),
 FOREIGN KEY (FLIGHT_ID) REFERENCES FLIGHTS(ID) ON DELETE CASCADE ON UPDATE CASCADE
);