#!/bin/sh
# Archive Database backup script
# (c) 2005, 2006, 2007, 2008 Global Virtual Airlines Group. All Rights Reserved.

# Set archiving options
arc_util="pbzip2 -p2 -9 -c"

# Log Starting
echo `date +%H:%M:%S`' Starting'

# Set up mysql utility aliases
mysql="/usr/local/mysql/bin/mysql --socket=/var/run/mysql5/mysql.sock"
mysqldump="/usr/local/mysql/bin/mysqldump --socket=/var/run/mysql5/mysql.sock"

# Goto backup directory
cd /home/backup/db

# Dump Navigation Data
echo `date +%H:%M:%S`' Writing Approach Charts'
$mysqldump -C -n -t -K -q --single-transaction `cat /usr/local/etc/sqlbackup` common CHARTS CHARTIMGS | gzip -5 > old/charts.sql.gz

# Write last backup time
echo `date +%H:%M:%S`' Write last backup time'
echo 'SELECT UNIX_TIMESTAMP(NOW())' | $mysql -h mysql.deltava.org -N `cat /usr/local/etc/sqlbackup` acars > lastbackuptime

# Dump ACARS position archive
echo `date +%H:%M:%S`' Writing ACARS Position Archive'
$mysqldump -C -n -t -K -q --single-transaction -h mysql.deltava.org `cat /usr/local/etc/sqlbackup` acars POSITION_ARCHIVE | $arc_util > old/acars_pos.sql.bz2

# Dump Image Gallery Data
echo `date +%H:%M:%S`' Writing DVA Image Gallery'
$mysqldump -C -n -t -K --single-transaction -q -h mysql.deltava.org `cat /usr/local/etc/sqlbackup` dva GALLERY GALLERYSCORE | $arc_util > old/dva_gallery.sql.bz2
echo `date +%H:%M:%S`' Writing AFV Image Gallery'
$mysqldump -C -n -t -K --single-transaction -q -h mysql.deltava.org `cat /usr/local/etc/sqlbackup` afv GALLERY GALLERYSCORE | $arc_util > old/afv_gallery.sql.bz2

# Change file permissions
echo `date +%H:%M:%S`' Setting file permissions'
chown -R root:gva old/*.sql.bz2
chmod 640 old/*.sql.bz2

# Log Completion
echo `date +%H:%M:%S`' Complete'
