#!/bin/sh
# Configuration backup script
# (c) 2005, 2006 Global Virtual Airlines Group. All Rights Reserved.

# Goto backup directory
cd /home/backup/cfg

# Copy configuration files
tar vcfz authlib.tar.gz /usr/local/etc/authlib
tar vcfz awstats.tar.gz /usr/local/etc/awstats
tar vcfz spamassassin.tar.gz /etc/mail/spamassassin
tar vcfz tomcat.tar.gz /usr/local/tomcat/conf /usr/local/tomcat/bin
tar vcfz postfix.tar.gz /etc/postfix
tar vcfz imapd.tar.gz /usr/lib/courier-imap/etc
tar vcfz mysql.tar.gz /home/mysql/my.cnf
tar vcfz ts2.tar.gz /usr/local/ts2
tar vcfz crontabs.tar.gz /var/spool/cron/tabs

# Update permissions
chmod 660 *.tar.gz
chown backup:gva *.tar.gz
