#!/bin/bash
# Chart backup script
# (c) 2011 Global Virtual Airlines Group. All Rights Reserved.

# Set archiving/mysqldump options
arc_util="pbzip2 -p2 -3 -b20 -c"
dump_opt="--single-transaction -e -K -n -q"

# Log Starting
echo `date +%H:%M:%S`' Starting'

# Goto backup directory
cd /home/backup/db

# Set up mysql utility aliases
mysql="/usr/local/mysql/bin/mysql --socket=/var/run/mysql/mysql.sock --skip-column-names"
mysqldump="/usr/local/mysql/bin/mysqldump --socket=/var/run/mysql/mysql.sock"

# Dump Charts
echo `date +%H:%M:%S`' Writing Approach Chart data'
$mysqldump $dump_opt `cat /usr/local/etc/sqlbackup` common CHARTS CHARTIMGS | $arc_util > charts.sql.bz2

# Change file permissions
echo `date +%H:%M:%S`' Setting file permissions'
chown -R backup:gva charts.sql.bz2
chmod 640 charts.sql.bz2

# Log Completion
echo `date +%H:%M:%S`' Complete'
exit 0
