#!/bin/sh
# Database backup script
# (c) 2005, 2006 Global Virtual Airlines Group. All Rights Reserved.

# Goto backup directory
cd /home/backup/db
mv *.bz2 old

# Backup AWSTATS tables
tar cfvj awstats.tar.bz2 /home/awstats

# Set up mysql utility aliases
alias mysql='/usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock'
alias mysqldump='/usr/local/mysql5/bin/mysqldump --socket=/var/run/mysql5/mysql.sock'

# Dump core table
echo 'Writing mySQL configuration'
mysqldump -e -h mysql.deltava.org mysql `cat /usr/local/etc/sqlbackup` | bzip2 -9 > mysql.sql.bz2

# Dump table definitions
echo 'Writing table definitions'
mysqldump -e -K -d -h mysql.deltava.org `cat /usr/local/etc/sqlbackup` common > common.sql
mysqldump -e -K -d -h mysql.deltava.org `cat /usr/local/etc/sqlbackup` acars > acars.sql
mysqldump -e -K -d -h mysql.deltava.org `cat /usr/local/etc/sqlbackup` dva > dva.sql
mysqldump -e -K -d -h mysql.deltava.org `cat /usr/local/etc/sqlbackup` afv > afv.sql
tar cfvj create_tables.tar.bz2 *.sql
rm *.sql

# Dump e-mail data
echo 'Writing e-mail configuration'
mysqldump -e -K -h mysql.deltava.org `cat /usr/local/etc/sqlbackup` postfix | bzip2 -9 > postfix.sql.bz2

# Dump TeamSpeak data
echo 'Writing TeamSpeak configuration'
mysqldump -e -K -h mysql.deltava.org `cat /usr/local/etc/sqlbackup` teamspeak | bzip2 -9 > teamspeak.sql.bz2

# Dump Common data/Water Cooler/Events
echo 'Writing Common data'
mysqldump -e -n -t -K -h mysql.deltava.org `cat /usr/local/etc/sqlbackup` common AIRLINEINFO TZ AIRCRAFT AIRCRAFT_AIRLINE AIRLINES APP_AIRLINES AIRLINE_CODES AIRPORTS AIRPORT_AIRLINE AIRPORT_CODES USERDATA AUTH AUTH_ALIAS OCEANIC ISSUES ISSUE_COMMENTS SYSINFODATA | bzip2 -9 > common.sql.bz2
mysqldump -e -n -t -K -h mysql.deltava.org `cat /usr/local/etc/sqlbackup` common EVENTS EVENT_AIRPORTS EVENT_CHARTS EVENT_PLANS EVENT_EQTYPES EVENT_SIGNUPS | bzip2 -9 > events.sql.bz2

# Dump Water Cooler
echo 'Writing Water Cooler'
mysqldump -e -n -t -K -q -h mysql.deltava.org `cat /usr/local/etc/sqlbackup` common COOLER_CHANNELS COOLER_CHANNELINFO COOLER_THREADS COOLER_THREADHISTORY COOLER_POSTS COOLER_NOTIFY COOLER_POLLS COOLER_VOTES COOLER_IMGURLS | bzip2 -9 > cooler.sql.bz2

# Dump Navigation Data if we're doing a full backup
if [ "$1" = "full" ]
then
  echo 'Writing Navigation Data'
  mysqldump -e -n -t -K -q -h mysql.deltava.org `cat /usr/local/etc/sqlbackup` common NAVDATA SID_STAR AIRWAYS CHARTS | bzip2 -9 > navdata.sql.bz2
  
  echo 'Writing ACARS Position Archive'
  mysqldump -e -n -t -K -q -h mysql.deltava.org `cat /usr/local/etc/sqlbackup` acars POSITION_ARCHIVE | bzip2 -9 > acars_pos.sql.bz2
  
  echo 'Write last backup time'
  echo 'SELECT UNIX_TIMESTAMP(NOW())' | mysql -h mysql.deltava.org -N `cat /usr/local/etc/sqlbackup` acars > lastbackuptime
else
  echo 'Writing Incremental ACARS Positions'
  mysqldump -e -n -t -K -q -h mysql.deltava.org `cat /usr/local/etc/sqlbackup` --where="UNIX_TIMESTAMP(REPORT_TIME) > `cat lastbackuptime`" acars POSITION_ARCHIVE | bzip2 -9 > acars_pos_inc.sql.bz2
fi

# Dump ACARS data
echo 'Writing ACARS data'
mysqldump -e -n -t -K -h mysql.deltava.org `cat /usr/local/etc/sqlbackup` acars CONS FLIGHTS POSITIONS ERRORS MESSAGES | bzip2 -9 > acars.sql.bz2

# Dump DVA database
echo 'Writing DVA database'
mysqldump -e -n -t -K -q -h mysql.deltava.org `cat /usr/local/etc/sqlbackup` dva PILOTS RATINGS ROLES PIREPS PIREP_COMMENT ACARS_PIREPS PROMO_EQ ASSIGNMENTS ASSIGNLEGS DOCS FLEET VIDEOS NEWSLETTERS EQTYPES EQRATINGS NEWS NOTAMS PILOT_MAP SIGNATURES STAFF STATUS_UPDATES BLOG BLOGCOMMENTS GALLERYSCORE | bzip2 -9 > dva.sql.bz2
mysqldump -e -n -t -K -h mysql.deltava.org `cat /usr/local/etc/sqlbackup` dva APPLICANTS APPEXAMS APPQUESTIONS CHECKRIDES CR_DESCS EXAMINFO QUESTIONINFO QUESTIONMINFO QE_INFO EXAMS EXAMQUESTIONS EXAMQUESTIONSM TXREQUESTS HELPDESK HELPDESK_COMMENTS | bzip2 -9 > dva_test.sql.bz2
mysqldump -e -n -t -K -h mysql.deltava.org `cat /usr/local/etc/sqlbackup` dva DOWNLOADS INACTIVITY HELP LOG_APP LOG_TASK MSG_TEMPLATES EMAIL_VALIDATION SYS_COMMANDS SYS_HTTPLOG SYS_TASKS SYS_REFERERS | bzip2 -9 > dva_sys.sql.bz2
mysqldump -e -n -t -K -h mysql.deltava.org `cat /usr/local/etc/sqlbackup` dva SCHEDULE ROUTES SELCAL | bzip2 -9 > dva_sched.sql.bz2
mysqldump -e -n -t -K -h mysql.deltava.org `cat /usr/local/etc/sqlbackup` dva CERTS CERTREQS CERTEXAMS CERTDOCS CERTVIDEOS COURSES COURSEPROGRESS COURSECHAT INSCALENDAR INSLOG | bzip2 -9 > dva_academy.sql.bz2

# Dump AFV database
echo 'Writing AFV database'
mysqldump -e -n -t -K -h mysql.deltava.org `cat /usr/local/etc/sqlbackup` afv PILOTS RATINGS ROLES PIREPS PIREP_COMMENT ACARS_PIREPS PROMO_EQ ASSIGNMENTS ASSIGNLEGS DOCS FLEET EQTYPES EQRATINGS NEWS NOTAMS PILOT_MAP SIGNATURES STAFF STATUS_UPDATES GALLERYSCORE | bzip2 -9 > afv.sql.bz2
mysqldump -e -n -t -K -h mysql.deltava.org `cat /usr/local/etc/sqlbackup` afv APPLICANTS APPEXAMS APPQUESTIONS CHECKRIDES CR_DESCS EXAMINFO QUESTIONINFO QUESTIONMINFO QE_INFO EXAMS EXAMQUESTIONS EXAMQUESTIONSM TXREQUESTS HELPDESK HELPDESK_COMMENTS | bzip2 -9 > afv_test.sql.bz2
mysqldump -e -n -t -K -h mysql.deltava.org `cat /usr/local/etc/sqlbackup` afv DOWNLOADS INACTIVITY HELP LOG_APP LOG_TASK MSG_TEMPLATES EMAIL_VALIDATION SYS_COMMANDS SYS_HTTPLOG SYS_TASKS SYS_REFERERS | bzip2 -9 > afv_sys.sql.bz2
mysqldump -e -n -t -K -h mysql.deltava.org `cat /usr/local/etc/sqlbackup` afv SCHEDULE ROUTES SELCAL | bzip2 -9 > afv_sched.sql.bz2

# Dump Galleries if we're doing a full backup
if [ "$1" = "full" ]
then
  echo 'Writing DVA Image Gallery'
  mysqldump -e -n -t -K -q -h mysql.deltava.org `cat /usr/local/etc/sqlbackup` dva GALLERY | bzip2 -4 > dva_gallery.sql.bz2
  echo 'Writing AFV Image Gallery'
  mysqldump -e -n -t -K -q -h mysql.deltava.org `cat /usr/local/etc/sqlbackup` afv GALLERY | bzip2 -4 > afv_gallery.sql.bz2
else  
  echo 'Writing Incremental DVA Image Gallery'
  mysqldump -e -n -t -K -q -h mysql.deltava.org `cat /usr/local/etc/sqlbackup` --where="UNIX_TIMESTAMP(DATE) > `cat lastbackuptime`" dva GALLERY | bzip2 -4 > dva_gallery_inc.sql.bz2
  echo 'Writing Incremental AFV Image Gallery'
  mysqldump -e -n -t -K -q -h mysql.deltava.org `cat /usr/local/etc/sqlbackup` --where="UNIX_TIMESTAMP(DATE) > `cat lastbackuptime`" afv GALLERY | bzip2 -4 > afv_gallery_inc.sql.bz2
fi

# Change file permissions
chown -R backup:gva *
chmod 640 *
chmod 750 old
