#!/bin/sh
# Database restore script
# (c) 2005, 2006 Global Virtual Airlines Group. All Rights Reserved.

# Build TEMP directory
mkdir /tmp/dbrestore
cd /tmpdbrestore

# Rebuild tables
echo 'Recreating Tables'
cp /home/backup/db/create_tables.tar.bz2 .
tar xvfj create_tables.tar.bz2
/usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -p$1 common < common.sql
/usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -p$1 acars < acars.sql
/usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -p$1 afv < afv.sql
/usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -p$1 dva < dva.sql
rm *.sql

# Rebuild databases
echo 'Loading Common Data'
lzcat /home/backup/db/common.sql.lzma | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -p$1 common
lzcat /home/backup/db/events.sql.lzma | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -p$1 common

echo 'Restoring Postfix/Teampseak Data'
lzcat /home/backup/db/postfix.sql.lzma | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -p$1 postfix
lzcat /home/backup/db/teamspeak.sql.lzma | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -p$1 teamspeak

echo 'Restoring DVA data'
lzcat /home/backup/db/dva.sql.lzma | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -p$1 dva
lzcat /home/backup/db/dva_academy.sql.lzma | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -p$1 dva
lzcat /home/backup/db/dva_sched.sql.lzma | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -p$1 dva
lzcat /home/backup/db/dva_sys.sql.lzma | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -p$1 dva
lzcat /home/backup/db/dva_test.sql.lzma | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -p$1 dva

echo 'Restoring AFV data'
lzcat /home/backup/db/afv.sql.lzma | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -p$1 afv
lzcat /home/backup/db/afv_sched.sql.lzma | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -p$1 afv
lzcat /home/backup/db/afv_sys.sql.lzma | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -p$1 afv
lzcat /home/backup/db/afv_test.sql.lzma | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -p$1 afv

echo 'Restoring Water Cooler'
lzcat /home/backup/db/cooler.sql.lzma | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -p$1 common

echo 'Restoring ACARS data'
lzcat /home/backup/db/acars.sql.lzma | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -p$1 acars
lzcat /home/backup/db/acars_pos_inc.sql.lzma | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -p$1 acars

echo 'Restoring Navigation Data'
lzcat /home/backup/db/navdata.sql.lzma | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -p$1 common

echo 'Restoring ACARS position archive'
lzcat /home/backup/db/acars_pos.sql.lzma | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -p$1 acars

echo 'Restoring Image Galleries'
lzcat /home/backup/db/dva_gallery.sql.lzma | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -p$1 dva
lzcat /home/backup/db/afv_gallery.sql.lzma | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -p$1 afv
