#!/bin/sh
# Database restore script
# (c) 2005, 2006 Global Virtual Airlines Group. All Rights Reserved.

# Build TEMP directory
mkdir /tmp/dbrestore
cd /tmpdbrestore

# Rebuild tables
echo 'Recreating Tables'
cp /home/backup/db/create_tables.tar.bz2 .
bzip2 -d create_tables.tar.bz2 | tar xvf create_tables.tar
rm create_tables.tar
/usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -pgv@root# common < common.sql
/usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -pgv@root# acars < acars.sql
/usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -pgv@root# afv < afv.sql
/usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -pgv@root# dva < dva.sql
rm *.sql

# Rebuild databases
echo 'Loading Common Data'
bzcat /home/backup/db/common.sql.bz2 | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -pgv@root# common
bzcat /home/backup/db/events.sql.bz2 | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -pgv@root# common

echo 'Restoring Postfix/Teampseak Data'
bzcat /home/backup/db/postfix.sql.bz2 | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -pgv@root# postfix
bzcat /home/backup/db/teamspeak.sql.bz2 | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -pgv@root# teamspeak

echo 'Restoring DVA data'
bzcat /home/backup/db/dva.sql.bz2 | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -pgv@root# dva
bzcat /home/backup/db/dva_academy.sql.bz2 | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -pgv@root# dva
bzcat /home/backup/db/dva_sched.sql.bz2 | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -pgv@root# dva
bzcat /home/backup/db/dva_sys.sql.bz2 | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -pgv@root# dva
bzcat /home/backup/db/dva_test.sql.bz2 | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -pgv@root# dva

echo 'Restoring AFV data'
bzcat /home/backup/db/afv.sql.bz2 | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -pgv@root# afv
bzcat /home/backup/db/afv_sched.sql.bz2 | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -pgv@root# afv
bzcat /home/backup/db/afv_sys.sql.bz2 | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -pgv@root# afv
bzcat /home/backup/db/afv_test.sql.bz2 | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -pgv@root# afv

echo 'Restoring Water Cooler'
bzcat /home/backup/db/cooler.sql.bz2 | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -pgv@root# common

echo 'Restoring ACARS data'
bzcat /home/backup/db/acars.sql.bz2 | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -pgv@root# acars
bzcat /home/backup/db/acars_pos_inc.sql.bz2 | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -pgv@root# acars

echo 'Restoring Navigation Data'
bzcat /home/backup/db/old/navdata.sql.bz2 | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -pgv@root# common

echo 'Restoring ACARS position archive'
bzcat /home/backup/db/old/acars_pos.sql.bz2 | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -pgv@root# acars

echo 'Restoring Image Galleries'
bzcat /home/backup/db/old/dva_gallery.sql.bz2 | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -pgv@root# dva
bzcat /home/backup/db/old/afv_gallery.sql.bz2 | /usr/local/mysql5/bin/mysql --socket=/var/run/mysql5/mysql.sock -pgv@root# afv
