#!/bin/bash
# System daemon checking script
# (c) 2005-2009 Global Virtual Airlines Group. All Rights Reserved.

if [ -f "/var/run/siteDown.flag" ]
then
 echo "/var/run/siteDown.flag set - aborting"
 exit
fi

if [ -f "/var/run/named.pid" ]
then
  if [ -d "/proc/`cat /var/run/named.pid`" ]
  then
   echo "BIND (DNS Server) is alive"
  else
   echo "BIND (DNS Server) is DOWN"
   /etc/init.d/named start
  fi
else
 echo "BIND (DNS Server) is DOWN - no pid"
 /etc/init.d/named start
fi

if [ -f "/var/run/mysql.pid" ]
then
  if [ -d "/proc/`cat /var/run/mysql.pid`" ]
  then
   echo "mySQL 5 (Database Server) is alive"
  else
   echo "mySQL 5 (Database Server) is DOWN"
   /etc/init.d/mysql start
  fi
else
 echo "mySQL 5 (Database Server) is DOWN - no pid"
 /etc/init.d/mysql start
fi

if [ -f "/var/run/tomcat60.pid" ]
then
  if [ -d "/proc/`cat /var/run/tomcat60.pid`" ]
  then
   echo "Tomcat (Application Server) is alive"
  else
   echo "Tomcat (Application Server) is DOWN"
   /etc/init.d/tomcat start
  fi
else
  echo "Tomcat (Application Server) is DOWN - no pid"
  /etc/init.d/tomcat start
fi

if [ -f "/var/run/httpd.pid" ]
then
  if [ -d "/proc/`cat /var/run/httpd.pid`" ]
  then
   echo "Apache (Web Server) is alive"
  else
   echo "Apache (Web Server) is DOWN"
   /etc/init.d/httpd start
  fi
else
  echo "Apache (Web Server) is DOWN - no pid"
  /etc/init.d/httpd start
fi

#if [ -f "/var/run/slapd.pid" ]
#then
#  if [ -d "/proc/`cat /var/run/slapd.pid`" ]
#  then
#   echo "OpenLDAP (Authentication Server) is alive"
#  else
#   echo "OpenLDAP (Authentication Server) is DOWN"
#   /etc/init.d//ldapctl start
#  fi
#else
#  echo "OpenLDAP (Authentication Server) is DOWN - no pid"
#  /etc/init.d//ldapctl start
#fi

if [ -f "/var/run/postfix.pid" ]
then
  if [ -d "/proc/`pidof master`" ]
  then
   echo "PostFix (SMTP Server) is alive"
  else
   echo "PostFix (SMTP Server) is DOWN"
   /etc/init.d/postfix start
  fi
else
  echo "PostFix (SMTP Server) is DOWN - no pid"
  /etc/init.d/postfix start
fi

if [ -f "/var/run/spamd.pid" ]
then
  if [ -d "/proc/`cat /var/run/spamd.pid`" ]
  then
   echo "SpamAssassin (Spam Filtering Server) is alive"
  else
   echo "SpamAssassin (Spam Filtering Server) is DOWN"
   /etc/init.d/spamd start
  fi
else
 echo "SpamAssassin (Spam Filtering Server) is DOWN - no pid"
 /etc/init.d/spamd start
fi

if [ -f "/var/run/authdaemon.pid" ]
then
  if [ -d "/proc/`cat /var/run/authdaemon.pid`" ]
  then
   echo "IMAP Authentication Server is alive"
  else
   echo "IMAP Authentication Server is DOWN"
   /etc/init.d/authdaemond start
  fi
else
 echo "IMAP Authentication Server is DOWN - no pid"
 /etc/init.d/authdaemond start
fi

if [ -f "/var/run/imapd.pid" ]
then
  if [ -d "/proc/`cat /var/run/imapd.pid`" ]
  then
   echo "Courier (IMAP Server) is alive"
  else
   echo "Courier (IMAP Server) is DOWN"
   /etc/init.d/imapd start
  fi
else
 echo "Courier (IMAP Server) is DOWN - no pid"
 /etc/init.d/imapd start
fi

if [ -f "/var/run/ts2.pid" ]
then
  if [ -d "/proc/`cat /var/run/ts2.pid`" ]
  then
    echo "TeamSpeak (Voice Server) is alive"
  else
    echo "TeamSpeak (Voice Server) is DOWN"
    /etc/init.d/ts2 start
  fi
else
  echo "TeamSpeak (Voice Server) is DOWN - no pid"
  /etc/init.d/ts2 start
fi

if [ -f "/var/run/clamd.pid" ]
then
  if [ -d "/proc/`cat /var/run/clamd.pid`" ]
  then
    echo "ClamAV (Anti-VIrus Server) is alive"
  else
    echo "ClamAV (Anti-VIrus Server) is DOWN"
    /etc/init.d/clamd start
  fi
else
  echo "ClamAV (Anti-Virus Server) is DOWN - no pid"
  /etc/init.d/clamd start
fi

# Check SSH blacklist process
if [ -f "/var/run/blacklist.pid" ]
then
  if [ -d "/proc/`cat /var/run/blacklist.pid`" ]
  then
  	echo "Blacklist (SSH blacklist daemon) is alive"
  else
    echo "Blacklist (SSH blacklist daemon) is DOWN"
    /etc/init.d/blacklist start
  fi
else
  echo "Blacklist (SSH blacklist daemon) is DOWN - no pid"
  /etc/init.d/blacklist start
fi

# Check HTTP health check
if [ -f "/var/run/tomcat60.pid" ]
then
	wget -nv -O /dev/null -o /tmp/healthcheck.log --timeout=3 --tries=1 --no-cache --user-agent=IsAlive/1.0 http://www.deltava.org/healthcheck.ws
	errorLines=`grep ERROR /tmp/healthcheck.log | wc -l`
	rm /tmp/healthcheck.log
	if [ "$?" -ne "0" ] || [ $errorLines -ne "0" ]
	then
		echo "Site appears DOWN - Health Check failed"
		killall -9 java
		sleep 1.5
		echo "Archiving Tomcat log"
		tomcat_log_reset
		/etc/init.d/tomcat start
	else
		echo "Health Check is OK"
	fi
fi		

# if [ -f "/var/run/fsd.pid" ]
# then
#   if [ -d "/proc/`cat /var/run/fsd.pid`" ]
#   then
#     echo "FSD (FS Multiplayer Server) is alive"
#   else
#     echo "FSD (FS Multiplayer Server) is DOWN"
#     /etc/init.d/fsd start
#   fi
# else
#   echo "FSD (FS Multiplayer Server) is DOWN - no pid"
#   /etc/init.d/fsd start
# fi
