#!/bin/bash
# Maildir backup script
# (c) 2006, 2008 Global Virtual Airlines Group. All Rights Reserved.

# Set archiving options
arc_util="pbzip2 -p2 -9 -c"

# Goto backup directory
cd /home/backup/mail

# Backup maildirs
tar cf - /home/mail | $arc_util > mailbox.tar.bz2

# Update permissions
chmod 640 *.tar.bz2
chown backup:root *.tar.bz2
