#!/bin/bash
# IMAP Mailbox directory creation script
# (c) 2005, 2008 Global Virtual Airlines Group. All Rights Reserved.

# Check for existing mailbox
if [ -d "$2/$1" ]
then
  echo "Mailbox folder $2/$1 already exists!"
  exit 1
fi

# Create the mailbox
mkdir $2/$1
mkdir $2/$1/cur
mkdir $2/$1/new
mkdir $2/$1/tmp
mkdir $2/$1/SPAM
mkdir $2/$1/SPAM/cur
mkdir $2/$1/SPAM/new
mkdir $2/$1/SPAM/tmp
chown -R postfix:postfix $2/$1

# Log success
echo "Mailbox $2/$1 succesfully created"
exit 1
