#! /bin/csh
# Script to mark the web site as up.
# (c) 2005 Delta Virtual Airlines.
#

if [ -e "/var/run/siteDown.flag" ]
then
 echo 'Clearing Site Down flag'
 rm /var/run/siteDown.flag
fi

if [ -e "/usr/local/www/deltava.org/www/index.html" ]
then
 echo 'Clearing Delta Virtual Airlines Site Down page'
 rm /usr/local/www/deltava.org/www/index.html
fi

if [ -e "/usr/local/www/afva.net/www/index.html" ]
then
 echo 'Clearing Aviation Francais Virtuel Site Down page'
 rm /usr/local/www/afva.net/www/index.html
fi

