#!/bin/sh
# Script to mark the web site as down.
# Copyright 2005 Global Virtual Airlines Group. All Rights Reserved.

if [ ! -e "/var/run/siteDown.flag" ]
then
 echo 'Setting Site Down flag'
 touch /var/run/siteDown.flag
fi

echo 'Setting Delta Virtual Airlines Site Down page'
cd /usr/local/www/deltava.org/www
cp error500.html index.html

echo 'Setting Aviation Francais Virtuel Site Down page'
cd /usr/local/www/afva.net/www
cp error500.html index.html
