#!/bin/bash
# Tomcat log backup script
# (c) 2011 Global Virtual Airlines Group. All Rights Reserved.

# Set archiving options
arc_util="pbzip2 -p2 -9 -b20 -c"

log_src_path="/var/log/tomcat"
log_dst_path="/home/backup/logs/tomcat"

# Backup files
$arc_util $log_src_path/catalina.log.2*

# Move files
mv $log_src_path/catalina.log.*.bz2 $log_dst_path
exit 0
 