#!/bin/sh
# Tomcat log reset script
# (c) 2005, 2007 Global Virtual Airlines Group. All Rights Reserved.

bzip2 -9 /var/log/tomcat/catalina.out
chgrp gva /var/log/tomcat/catalina.out.bz2
chmod 664 /var/log/tomcat/catalina.out.bz2
mv /var/log/tomcat/catalina.out.bz2 /var/log/tomcat/catalina.out.`date +%b%d%H%M%S`.bz2
touch /var/log/tomcat/catalina.out
chown www /var/log/tomcat/catalina.out
