#!/bin/sh
# Tomcat restart script
# (c) 2005, 2006 Global Virtual Airlines Group. All Rights Reserved.

# Mark side as down
touch /var/run/siteDown.flag

# Stop Tomcat
echo "Shutting down Tomcat"
/usr/local/tomcat/bin/shutdown.sh
sleep 3

if [ -f "/var/run/tomcat55.pid" ]
then
 if [ -d "/proc/`cat /var/run/tomcat55.pid`" ]
 then
  echo "Killing process `cat /var/run/tomcat55.pid`"
  kill -9 `cat /var/run/tomcat55.pid`
 fi
fi

# Clean up
echo "Cleaning out logs/PID file"
rm /var/run/tomcat55.pid
rm /var/log/tomcat/*
touch /var/log/tomcat/catalina.out
chown www /var/log/tomcat/catalina.out

# Start Tomcat and Apache
echo "Restarting Tomcat"
/usr/local/tomcat/bin/startup.sh

# Mark site as up
rm /var/run/siteDown.flag
