#!/bin/bash
# Tomcat upgrade script
# (c) 2006, 2010 Global Virtual Airlines Group. All Rights Reserved.

# Check the version argument is preset
if [ "$1" == "" ]
then
 echo "tomcat_upgrade <version> ..."
 exit 1
fi

# Check that the version exists
if [ ! -d "/usr/local/apache-tomcat-$1" ]
then
 echo "Cannot find /usr/local/apache-tomcat-$1"
 exit 2
fi

# Go to the directory
cd /usr/local/apache-tomcat-$1

# Clean out default webapps
echo "Cleaning default installation"
rm -Rd webapps/docs
rm -Rd webapps/examples
rm -Rd webapps/ROOT
rm temp/*
rm LICENSE
rm NOTICE
rm RELEASE-NOTES
rm RUNNING.txt

# Nuke bad stuff in bin
echo "Removing Windows-specific files"
rm bin/*.bat
rm bin/*.tar.gz

# Create the logging symlink
rm -Rd logs
ln -s /var/log/tomcat logs

# Copy over the work directory
echo "Copying work directory"
cp -R /usr/local/tomcat/work/* work

# Copy over common libraries
echo "Copying libraries"
cp -u /usr/local/tomcat/lib/* lib

# Copy over configuration files
echo "Copying Tomcat configuration"
cp /usr/local/tomcat/conf/server.xml conf
cp /usr/local/tomcat/conf/tomcat-users.xml conf
cp /usr/local/tomcat/conf/logging.properties conf
cp /usr/local/tomcat/bin/catalina.sh bin

# Change permissions
echo "Changing file permissions"
chown -R www:www *
chown -R www:gva lib
chmod 664 lib

# Switch to /usr/local
cd /usr/local
echo "Tomcat Upgrade complete"
