CREATE TABLE BLOGCOMMENTS (
 ID						INTEGER UNSIGNED NOT NULL,
 CREATED				DATETIME NOT NULL,
 AUTHOR					VARCHAR(64) NOT NULL,
 EMAIL					VARCHAR(128),
 BODY					TEXT NOT NULL,
 PRIMARY KEY (ID, CREATED),
 FOREIGN KEY (ID) REFERENCES BLOG(ID) ON DELETE CASCADE ON UPDATE CASCADE
);