CREATE TABLE BLOG (
 ID						INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 CREATED				DATETIME NOT NULL,
 AUTHOR_ID				INTEGER UNSIGNED NOT NULL,
 TITLE					VARCHAR(128) NOT NULL,
 PRIVATE				BOOL DEFAULT 0,
 LOCKED					BOOL DEFAULT 0,
 BODY					TEXT NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (AUTHOR_ID) REFERENCES common.USERDATA(ID) ON UPDATE CASCADE,
);