#!/bin/bash
# DHE parameter add script
# (c) 2022 Global Virtual Airlines Group. All Rights Reserved.

# Check for arguments
if [ "$2" == "" ]
then
 echo "add_ffdhe <cert file> <bits> ..."
 exit 1
fi

# Check for certificate file
if [ ! -f "$1" ]; then
	echo "Cannot find $1"
	exit 4
fi

# Check for DHE params file
if [ ! -f "/etc/ssl/private/ffdhe$2.pem" ]; then
	echo "Cannot find /etc/ssl/private/ffdhe$2.pem"
	exit 2
fi

# Check if cert already has DH params
DH_CNT=$(grep "DH PARAM" $1 | wc -l)
if [ $DH_CNT -ne 0 ]; then
	echo "DH Param count for $1 = $DH_CNT"
	exit 3
fi

# Check for the key file
KEY_FILE=$(echo "$1" | sed "s/crt/key")
if [ ! -f "$KEY_FILE" ]; then
	echo "Cannot find $KEY_FILE"
	exit 4
fi

# Check if the key file isn't ECC
if [ "$KEY_FILE" == *".ecc."* ]; then
	echo "$KEY_FILE is an ECC key"
	exit 5
fi

# Create the temp file
TMP_FILE=$(mktemp -q /tmp/bar.XXXXXX)
if [ $? -ne 0 ]; then
    echo "$0: Can't create temp file"
    exit 6
fi

# Cleanup temp file
trap 'rm -f -- "$TMP_FILE"' EXIT

# Combine cert with DH prime
echo "Adding ffdhe$2 to $1"
cat $1 > $TMP_FILE
cat /etc/ssl/private/ffdhe$2.pem >> $TMP_FILE
chmod 644 $TMP_FILE
mv $1 /etc/ssl/private/old
mv $TMP_FILE $1
exit 0
