#!/bin/bash
# Configuration backup script
# (c) 2005, 2006, 2007, 2010, 2011, 2012, 2020 Global Virtual Airlines Group. All Rights Reserved.

# Goto backup directory
cd /home/backup/cfg

# Copy configuration files
tar vcfz awstats.tar.gz /usr/local/etc/awstats
tar vcfz httpd.tar.gz /usr/local/apache24/conf
tar vcfz tomcat.tar.gz /usr/local/tomcat/conf
tar vcfz mysql.tar.gz /etc/my.cnf

# Update permissions
chmod 660 *.tar.gz
chown backup:users *.tar.gz

# Copy data directories
cd /home/www/deltava.org
tar --exclude="www/luke/*" -vcf /home/backup/sites/www.deltava.org.tar *

cd /home/www/afva.net
tar -vcf /home/backup/sites/www.afva.net.tar *
gzip -f7 /home/backup/sites/*.tar

# Update permissions
cd /home/backup/sites
chmod 660 *.tar.gz
chown backup:users *.tar.gz
exit 0
