#!/bin/bash
# System daemon checking script
# (c) 2005-2013 Global Virtual Airlines Group. All Rights Reserved.

if [ -f "/var/run/siteDown.flag" ]
then
 echo "/var/run/siteDown.flag set - aborting"
 exit
fi

# Check SSH blacklist process
if [ -f "/var/run/blacklist.pid" ]
then
  if [ -d "/proc/`cat /var/run/blacklist.pid`" ]
  then
  	echo "Blacklist (SSH blacklist daemon) is alive"
  else
    echo "Blacklist (SSH blacklist daemon) is DOWN"
    /etc/init.d/blacklist start
  fi
else
  echo "Blacklist (SSH blacklist daemon) is DOWN - no pid"
  /etc/init.d/blacklist start
fi

# Check bandwidth monitoring daemon
if [ -f "/var/run/bandwidthd.pid" ]
then
  if [ -d "/proc/`cat /var/run/bandwidthd.pid`" ]
  then
    echo "Bandwidthd (Bandwidth monitor) is alive"
  else
    echo "Bandwidthd (Bandwidth monitor) is DOWN"
    /etc/init.d/bandwidthd start
  fi
else
  echo "Bandwidthd (Bandwidth monitor) is DOWN - no pid"
  /etc/init.d/bandwidthd start
fi

# Check memcached daemon
if [ -f "/var/run/memcached.pid" ]
then
  if [ -d "/proc/`cat /var/run/memcached.pid`" ]
  then
    echo "Memcached (Cache server) is alive"
  else
    echo "Memcached (Cache server) is DOWN"
    /etc/init.d/memcached start
  fi
else
  echo "Memcached (Cache server) is DOWN - no pid"
  /etc/init.d/memcached start
fi

# Check VATSIM statistics daemon
if [ -f "/var/run/usageTrack.pid" ]
then
  if [ -d "/proc/`cat /var/run/usageTrack.pid`" ]
  then
    echo "VATSIM Stats (VATSIM statistics daemon) is alive"
  else
    echo "VATSIM Stats (VATSIM statistics daemon) is DOWN"
    /etc/init.d/vatsimstat start
  fi
else
  echo "VATSIM Stats (VATSIM statistics daemon) is DOWN - no pid"
  /etc/init.d/vatsimstat start
fi

# Check HTTP health check
if [ -f "/var/run/tomcat60.pid" ]
then
	wget -nv -O /tmp/healthcheck.log -o /dev/null --timeout=12 --tries=3 --no-cache --user-agent=IsAlive/1.0 http://www.deltava.org/healthcheck.ws
	errorLines=`grep "is OK" /tmp/healthcheck.log | wc -l`
	rm /tmp/healthcheck.log
	if [ $errorLines -ne "1" ]
	then
		echo "Site appears DOWN - Health Check failed"
		kill -3 `cat /var/run/tomcat60.pid`
		sleep 10
		kill -9 `cat /var/run/tomcat60.pid`
		sleep 2
		echo "Archiving Tomcat log"
		/usr/local/sbin/www/tomcat_log_reset
		/etc/init.d/tomcat start
	else
		echo "Health Check is OK"
	fi
fi		
