#!/bin/bash
# IMAP Remote Mailbox directory creation script
# (c) 2015 Global Virtual Airlines Group. All Rights Reserved.

HOST=$3
if [ "$HOST" == "" ]
then
 HOST="nephele.gvagroup.org"
fi

# Run the mailbox create command on another server
ssh www@$HOST "sudo /usr/local/sbin/www/mb_create $1 $2"
exit $?
