#!/bin/bash
# GVA Subversion Repository backup script
# (c) 2005, 2007, 2008, 2009, 2010, 2012, 2013, 2016, 2018, 2020 Global Virtual Airlines Group. All Rights Reserved.

# Set archiving options
arc_util="pbzip2 -9 -p2 -c"

# Goto backup directory
cd /home/backup/svn

# Get the current revision
LATEST=`svnlook youngest /home/svn`
LASTREV=`cat svn.revision_base`
echo "Latest=$LATEST, Last=$LASTREV"

# Check if we have anything to back up
if [ "$1" != "force" ] ;then
 if [ $LATEST -le $LASTREV ] ;then
  echo "Subversion repository unchanged Revision=$LATEST"
  exit 1
 fi
fi

# Back up the first 1000 revisions
REVISION=1000
while [ $REVISION -lt $LATEST ]
do

let "SR = $REVISION - 1000"
let "ER = $REVISION - 1"
ARCHIVE="svn_$ER.bz2"

if [ ! -f "/home/backup/svn/$ARCHIVE" ] ; then
 echo "Backing up revisions $SR-$ER"
 svnadmin dump /home/svn --revision $SR:$ER | $arc_util > $ARCHIVE
fi

((REVISION+=1000))

done

# Back up the last revisions
let "SR = $REVISION - 1000"
echo "Backing up revisions $SR-$LATEST"
svnadmin dump /home/svn --incremental --revision $SR:$LATEST --incremental | $arc_util > svn_top.bz2

# Save last revision
echo $LATEST > svn.revision_base

# Change file permissions
chown -R backup:users *.bz2
chmod 640 *
exit 0
