#!/bin/bash
# Tomcat upgrade script
# (c) 2006, 2010, 2012, 2016 Global Virtual Airlines Group. All Rights Reserved.

# Check the version argument is preset
if [ "$1" == "" ]
then
 echo "tomcat_upgrade <version> ..."
 exit 1
fi

# Check that the version exists
if [ ! -d "/usr/local/apache-tomcat-$1" ]
then
 echo "Cannot find /usr/local/apache-tomcat-$1"
 exit 2
fi

# Go to the directory
cd /usr/local/apache-tomcat-$1

# Clean out default webapps
echo "Cleaning default installation"
rm -r webapps/docs
rm -r webapps/examples
rm -r webapps/ROOT
rm temp/*
rm LICENSE
rm NOTICE
rm RELEASE-NOTES
rm RUNNING.txt
chmod 755 *

# Nuke bad stuff in bin
echo "Removing Windows-specific files"
rm bin/*.bat
rm bin/*.tar.gz
chmod 755 bin/*.sh
chmod 644 bin/*.jar
chmod 644 bin/*.xml

# Create the logging symlink
rm -r logs
ln -s /var/log/tomcat logs

# Copy over common libraries
echo "Copying libraries"
chmod 644 lib/*.jar
cp -pu /usr/local/tomcat/lib/* lib
cp /usr/local/tomcat/bin/jsvc bin

# Copy over configuration files
echo "Copying Tomcat configuration"
cp /usr/local/tomcat/conf/* conf
chgrp www conf/*
chmod 640 conf/*
mkdir conf/Catalina
chown root:www conf/Catalina
chmod 775 conf/Catalina

# Change permissions
echo "Changing file permissions"
chgrp www temp work
chgrp users lib
chmod 775 lib temp work

# Switch to /usr/local
cd /usr/local
echo "Tomcat Upgrade complete"
exit 0
