#!/bin/bash
# Database table size script
# (c) 2026 Global Virtual Airlines Group. All Rights Reserved.

export MYSQL_PWD=`cat /etc/sqlpwd.conf`
MYSQL=/usr/local/mysql/bin/mysql

$MYSQL -u root common < /usr/local/sbin/www/table_size.sql
exit 0
