CREATE TABLE STATUS_UPDATES (
 PILOT_ID			INTEGER UNSIGNED NOT NULL,
 CREATED			BIGINT UNSIGNED NOT NULL,
 AUTHOR_ID			INTEGER UNSIGNED NOT NULL,
 TYPE				SMALLINT,
 REMARKS			TEXT,
 PRIMARY KEY (PILOT_ID, CREATED),
 FOREIGN KEY (PILOT_ID) REFERENCES PILOTS(ID) ON DELETE CASCADE,
 FOREIGN KEY (AUTHOR_ID) REFERENCES PILOTS(ID) ON DELETE CASCADE
);

CREATE INDEX SU_TYP_IDX ON STATUS_UPDATES(TYPE);
