CREATE TABLE TXRIDES (
 ID						INTEGER UNSIGNED NOT NULL,
 CHECKRIDE_ID			INTEGER UNSIGNED NOT NULL,
 PRIMARY KEY (ID, CHECKRIDE_ID),
 FOREIGN KEY (ID) REFERENCES TXREQUESTS(ID) ON DELETE CASCADE,
 FOREIGN KEY (CHECKRIDE_ID) REFERENCES exams.CHECKRIDES(ID) ON DELETE CASCADE ON UPDATE CASCADE
);