CREATE TABLE TXREQUESTS (
 ID						INTEGER UNSIGNED NOT NULL,
 STATUS					SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 EQTYPE					VARCHAR(18) NOT NULL,
 ACTYPE					VARCHAR(15) NOT NULL,
 CREATED				DATETIME NOT NULL,
 RATING_ONLY			BOOLEAN NOT NULL DEFAULT FALSE,
 SIM                    SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES common.USERDATA(ID) ON DELETE CASCADE,
 FOREIGN KEY (EQTYPE) REFERENCES EQTYPES(EQTYPE) ON UPDATE CASCADE,
 FOREIGN KEY (ACTYPE) REFERENCES common.AIRCRAFT(NAME) ON UPDATE CASCADE
);