CREATE TABLE APPLICANT_STAGE_CHOICES (
 ID						INTEGER UNSIGNED NOT NULL,
 STAGE					TINYINT UNSIGNED NOT NULL,
 EQTYPE					VARCHAR(15) NOT NULL,
 PRIMARY KEY (ID, STAGE),
 FOREIGN KEY (ID) REFERENCES APPLICANTS(ID) ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY (EQTYPE) REFERENCES EQTYPES(EQTYPE) ON UPDATE CASCADE ON DELETE CASCADE
);