CREATE TABLE JOBPOSTINGS (
 ID					INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 CREATED			DATETIME NOT NULL,
 CLOSES				DATETIME NOT NULL,
 HIRE_MGR			INTEGER UNSIGNED NOT NULL,
 STATUS				TINYINT UNSIGNED NOT NULL,
 STAFF_ONLY			BOOLEAN NOT NULL DEFAULT FALSE,
 TITLE				VARCHAR(48) NOT NULL,
 SUMMARY			VARCHAR(128) NOT NULL,
 MINLEGS			SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 MINAGE				SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 BODY				TEXT CHARACTER SET utf8mb4 NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (HIRE_MGR) REFERENCES PILOTS(ID) ON UPDATE CASCADE
);