CREATE TABLE NOMINATIONS (
 ID				INTEGER UNSIGNED NOT NULL,
 QUARTER		SMALLINT UNSIGNED NOT NULL,
 SCORE			SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 STATUS			TINYINT UNSIGNED NOT NULL DEFAULT 0,
 PRIMARY KEY (ID, QUARTER),
 FOREIGN KEY (ID) REFERENCES PILOTS(ID) ON DELETE CASCADE ON UPDATE CASCADE
)