CREATE TABLE PILOT_ACCOMPLISHMENTS (
 PILOT_ID			INTEGER UNSIGNED NOT NULL,
 AC_ID				INTEGER UNSIGNED NOT NULL,
 DATE				DATETIME NOT NULL,
 PRIMARY KEY (PILOT_ID, AC_ID),
 FOREIGN KEY (PILOT_ID) REFERENCES PILOTS(ID) ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY (AC_ID) REFERENCES ACCOMPLISHMENTS(ID) ON UPDATE CASCADE ON DELETE CASCADE
);