CREATE TABLE EMAIL_VALIDATION (
 ID					INTEGER UNSIGNED NOT NULL,
 EMAIL				VARCHAR(96) NOT NULL,
 HASH				VARCHAR(64) NOT NULL,
 PRIMARY KEY(ID),
 FOREIGN KEY(ID) REFERENCES common.USERDATA(ID) ON DELETE CASCADE
);