CREATE TABLE NOMINATION_COMMENTS (
 ID				INTEGER UNSIGNED NOT NULL,
 QUARTER		SMALLINT UNSIGNED NOT NULL,
 AUTHOR			INTEGER UNSIGNED NOT NULL,
 CREATED		DATETIME NOT NULL,
 BODY			TEXT NOT NULL,
 PRIMARY KEY (ID, QUARTER, AUTHOR),
 FOREIGN KEY (ID, QUARTER) REFERENCES NOMINATIONS(ID, QUARTER) ON DELETE CASCADE,
 FOREIGN KEY (AUTHOR) REFERENCES PILOTS(ID) ON UPDATE CASCADE ON DELETE CASCADE
);