CREATE TABLE NOMINATION_COMMENTS (
 ID				INTEGER UNSIGNED NOT NULL,
 QUARTER		SMALLINT UNSIGNED NOT NULL,
 AUTHOR			INTEGER UNSIGNED NOT NULL,
 SUPPORT		BOOLEAN NOT NULL DEFAULT TRUE,
 CREATED		DATETIME NOT NULL,
 BODY			TEXT CHARACTER SET utf8mb4 NOT NULL,
 PRIMARY KEY (ID, QUARTER, AUTHOR),
 FOREIGN KEY (ID, QUARTER) REFERENCES NOMINATIONS(ID, QUARTER) ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY (AUTHOR) REFERENCES PILOTS(ID) ON UPDATE CASCADE ON DELETE CASCADE
);