CREATE TABLE SIGNATURES (
 ID						INTEGER UNSIGNED NOT NULL,
 WC_SIG 				MEDIUMBLOB NOT NULL,
 X						SMALLINT NOT NULL,
 Y						SMALLINT NOT NULL,
 PRIMARY KEY(ID),
 FOREIGN KEY(ID) REFERENCES PILOTS(ID) ON DELETE CASCADE ON UPDATE CASCADE
);