CREATE TABLE PILOT_PUSH (
 ID               INTEGER UNSIGNED NOT NULL,
 CREATED          DATETIME NOT NULL,
 AUTH             VARCHAR(64) NOT NULL,
 PUB256DH         VARCHAR(192) NOT NULL, 
 URL              VARCHAR(1024) NOT NULL,
 PRIMARY KEY (ID, URL),
 FOREIGN KEY (ID) REFERENCES PILOTS(ID) ON DELETE CASCADE ON UPDATE CASCADE
) CHARACTER SET latin1 ROW_FORMAT=Dynamic;