CREATE TABLE JOBAPROFILES (
 ID					INTEGER UNSIGNED NOT NULL,
 CREATED			DATETIME NOT NULL,
 AUTO_REUSE			BOOLEAN NOT NULL DEFAULT FALSE,
 BODY				TEXT CHARACTER SET utf8mb4 NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES PILOTS(ID) ON UPDATE CASCADE ON DELETE CASCADE
);