CREATE TABLE TXREQUESTS (
 ID						INTEGER UNSIGNED NOT NULL,
 STATUS					SMALLINT UNSIGNED,
 CHECKRIDE_ID			INTEGER UNSIGNED,
 EQTYPE					VARCHAR(18) NOT NULL,
 CREATED				DATETIME NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES PILOTS(ID) ON DELETE CASCADE,
 FOREIGN KEY (EQTYPE) REFERENCES EQTYPES(EQTYPE) ON UPDATE CASCADE
);