CREATE TABLE PILOTS (
 ID					INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 PILOT_ID			SMALLINT,
 FIRSTNAME			VARCHAR(32) NOT NULL,
 LASTNAME			VARCHAR(32) NOT NULL,
 STATUS				SMALLINT,
 LDAP_DN			VARCHAR(96) NOT NULL,
 EMAIL				VARCHAR(96),
 LOCATION			VARCHAR(48),
 IMHANDLE			VARCHAR(32),
 LEGACY_HOURS		DECIMAL(6,2),
 HOME_AIRPORT		CHAR(4) NOT NULL,
 EQTYPE				VARCHAR(15) DEFAULT 'CRJ-200',
 RANK				VARCHAR(24) NOT NULL,
 VATSIM_ID			VARCHAR(12),
 IVAO_ID			VARCHAR(12),
 CREATED			DATE NOT NULL,
 LOGINS				SMALLINT,
 LAST_LOGIN			DATETIME,
 LAST_LOGOFF		DATETIME,
 TZ					VARCHAR(32) DEFAULT 'US/Eastern',
 FILE_NOTIFY		BOOL,
 EVENT_NOTIFY		BOOL,
 NEWS_NOTIFY		BOOL,
 SHOW_EMAIL			SMALLINT,
 SHOW_WC_SIG		BOOL DEFAULT 1,
 SHOW_WC_SSHOTS		BOOL DEFAULT 1,
 UISCHEME			VARCHAR(32) DEFAULT 'legacy',
 LOGINHOSTNAME		VARCHAR(96),
 DFORMAT			VARCHAR(32) DEFAULT 'MM/dd/yyyy',
 TFORMAT			VARCHAR(16) DEFAULT 'HH:mm:ss',
 NFORMAT			VARCHAR(16) DEFAULT '#,###,##0.0',
 AIRPORTCODE		TINYINT UNSIGNED DEFAULT 0,
 MAPTYPE			TINYINT UNSIGNED DEFAULT 0,
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES common.USERDATA(ID),
 FOREIGN KEY (TZ) REFERENCES common.TZ(CODE) ON UPDATE CASCADE
);

CREATE INDEX PILOT_PID_IDX ON PILOTS(PILOT_ID);
CREATE INDEX PILOT_EQ_IDX ON PILOTS(EQTYPE);
CREATE INDEX PILOT_RANK_IDX ON PILOTS(RANK);
CREATE INDEX PILOT_STATUS_IDX ON PILOTS(STATUS);
