CREATE TABLE SIGNATURES (
 ID						INTEGER UNSIGNED NOT NULL,
 WC_SIG 				MEDIUMBLOB NOT NULL,
 X						SMALLINT UNSIGNED NOT NULL,
 Y						SMALLINT UNSIGNED NOT NULL,
 EXT					CHAR(3) NOT NULL,
 ISAPPROVED				BOOLEAN NOT NULL DEFAULT FALSE,
 MODIFIED				DATETIME NOT NULL,
 PRIMARY KEY(ID),
 FOREIGN KEY(ID) REFERENCES PILOTS(ID) ON DELETE CASCADE ON UPDATE CASCADE
);