CREATE TABLE RATINGS (
 ID				INTEGER UNSIGNED NOT NULL,
 RATING			VARCHAR(16) NOT NULL,
 PRIMARY KEY (ID, RATING),
 FOREIGN KEY (ID) REFERENCES PILOTS(ID) ON DELETE CASCADE,
 FOREIGN KEY (RATING) REFERENCES common.AIRCRAFT(NAME) ON UPDATE CASCADE ON DELETE CASCADE
);

