CREATE TABLE CERTS (
 ID				INTEGER UNSIGNED NOT NULL,
 CERTIFICATE	VARCHAR(32) NOT NULL,
 PRIMARY KEY (ID, CERTIFICATE),
 FOREIGN KEY (ID) REFERENCES PILOTS(ID) ON DELETE CASCADE,
 FOREIGN KEY (CERTIFICATE) REFERENCES CERTS(NAME) ON UPDATE CASCADE ON DELETE CASCADE
);