CREATE TABLE TXREQUESTS (
 ID						INTEGER UNSIGNED NOT NULL,
 STATUS					SMALLINT,
 CHECKRIDE_ID			INTEGER UNSIGNED,
 EQTYPE					VARCHAR(18) NOT NULL,
 CREATED				DATETIME NOT NULL,
 RATING_ONLY			BOOLEAN DEFAULT 0,
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES common.USERDATA(ID) ON DELETE CASCADE,
 FOREIGN KEY (EQTYPE) REFERENCES EQTYPES(EQTYPE) ON UPDATE CASCADE
);