CREATE TABLE COOLER_THREADHISTORY (
 ID						INTEGER UNSIGNED NOT NULL,
 CREATED				DATETIME NOT NULL,
 AUTHOR					INTEGER UNSIGNED NOT NULL,
 MESSAGE				VARCHAR(128) NOT NULL,
 PRIMARY KEY (ID, CREATED, AUTHOR),
 FOREIGN KEY (ID) REFERENCES COOLER_THREADS(ID) ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY (AUTHOR) REFERENCES USERDATA(ID) ON DELETE CASCADE ON UPDATE CASCADE
);