CREATE TABLE COOLER_VOTES (
 ID						INTEGER UNSIGNED NOT NULL,
 PILOT_ID				INTEGER UNSIGNED NOT NULL,
 OPT_ID					TINYINT NOT NULL,
 PRIMARY KEY (ID, PILOT_ID, OPT_ID),
 FOREIGN KEY (ID) REFERENCES COOLER_POLLS(ID) ON DELETE CASCADE,
 FOREIGN KEY (PILOT_ID) REFERENCES USERDATA(ID) ON DELETE CASCADE,
 FOREIGN KEY (OPT_ID) REFERENCES COOLER_POLLS(OPT_ID) ON DELETE CASCADE
);