CREATE TABLE COOLER_IMGURLS (
 ID						INTEGER UNSIGNED NOT NULL,
 SEQ					TINYINT UNSIGNED NOT NULL,
 URL					VARCHAR(192) NOT NULL,
 COMMENTS				VARCHAR(255),
 PRIMARY KEY (ID, SEQ),
 FOREIGN KEY (ID) REFERENCES COOLER_THREADS(ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE UNIQUE INDEX IMG_URL_IDX ON COOLER_IMGURLS(ID, URL);