CREATE TABLE COOLER_IMGURLS (
 ID						INTEGER UNSIGNED NOT NULL,
 URL					VARCHAR(192) NOT NULL,
 PRIMARY KEY (ID, URL),
 FOREIGN KEY (ID) REFERENCES COOLER_THREADS(ID) ON DELETE CASCADE ON UPDATE CASCADE
);