CREATE TABLE COOLER_CHANNELINFO (
 CHANNEL				VARCHAR(64) NOT NULL,
 INFOTYPE				SMALLINT,
 INFODATA				VARCHAR(32) NOT NULL,
 PRIMARY KEY (CHANNEL, INFOTYPE, INFODATA),
 FOREIGN KEY (CHANNEL) REFERENCES COOLER_CHANNELS(CHANNEL) ON DELETE CASCADE ON UPDATE CASCADE
);