CREATE TABLE COOLER_CHANNELS (
 CHANNEL					VARCHAR(64) NOT NULL,
 DESCRIPTION				VARCHAR(144) NOT NULL,
 ACTIVE						BOOLEAN NOT NULL DEFAULT 1,
 ALLOW_NEW					BOOLEAN NOT NULL DEFAULT 0,
 PRIMARY KEY (CHANNEL)
);