CREATE TABLE COOLER_REPORTS (
 THREAD_ID					INTEGER UNSIGNED NOT NULL,
 AUTHOR_ID                  INTEGER UNSIGNED NOT NULL,
 PRIMARY KEY (THREAD_ID, AUTHOR_ID),
 FOREIGN KEY (THREAD_ID) REFERENCES COOLER_THREADS(ID) ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY (AUTHOR_ID) REFERENCES USERDATA(ID)
);