CREATE TABLE COOLER_POSTSEARCH (
 THREAD_ID                  INTEGER UNSIGNED NOT NULL,
 POST_ID                    INTEGER UNSIGNED NOT NULL,
 MSGBODY                    TEXT NOT NULL,
 PRIMARY KEY (POST_ID, THREAD_ID),
 FULLTEXT (MSGBODY)
) Engine=MyISAM;

INSERT INTO COOLER_POSTSEARCH SELECT THREAD_ID, POST_ID, MSGBODY FROM COOLER_POSTS;

CREATE TRIGGER POST_ADD AFTER INSERT ON COOLER_POSTS FOR EACH ROW
 INSERT INTO COOLER_POSTSEARCH SET THREAD_ID=NEW.THREAD_ID, POST_ID=NEW.POST_ID, MSGBODY=NEW.MSGBODY;

CREATE TRIGGER POST_UPD AFTER UPDATE ON COOLER_POSTS FOR EACH ROW
 UPDATE COOLER_POSTSEARCH SET MSGBODY=NEW.MSGBODY WHERE (THREAD_ID=NEW.THREAD_ID) AND (POST_ID=NEW.POST_ID)
 AND (MSGBODY<>NEW.MSGBODY);

CREATE TRIGGER POST_DEL BEFORE DELETE ON COOLER_POSTS FOR EACH ROW
 DELETE FROM COOLER_POSTSEARCH WHERE (THREAD_ID=OLD.THREAD_ID) AND (POST_ID=OLD.POST_ID);

CREATE TRIGGER THREAD_DEL BEFORE DELETE ON COOLER_THREADS FOR EACH ROW
 DELETE FROM COOLER_POSTSEARCH WHERE (THREAD_ID=OLD.ID);
