CREATE TABLE COOLER_LASTREAD (
 ID                     INTEGER UNSIGNED NOT NULL,
 AUTHOR_ID              INTEGER UNSIGNED NOT NULL,
 LASTREAD               DATETIME NOT NULL,
 PRIMARY KEY (ID, AUTHOR_ID),
 FOREIGN KEY (ID) REFERENCES COOLER_THREADS(ID) ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY (AUTHOR_ID) REFERENCES USERDATA(ID)
);