CREATE TABLE COOLER_POLLS (
 ID					INTEGER UNSIGNED NOT NULL,
 OPT_ID				TINYINT AUTO_INCREMENT,
 NAME				VARCHAR(64) NOT NULL,
 PRIMARY KEY (OPT_ID, ID),
 CONSTRAINT UNIQUE (ID, NAME),
 FOREIGN KEY (ID) REFERENCES COOLER_THREADS(ID) ON DELETE CASCADE
);

CREATE INDEX POLL_ID_IDX ON COOLER_POLLS(ID);