CREATE TABLE COOLER_NOTIFY (
 THREAD_ID                  INTEGER UNSIGNED NOT NULL,
 USER_ID                  	INTEGER UNSIGNED NOT NULL,
 CREATED                    DATETIME NOT NULL,
 PRIMARY KEY (THREAD_ID, USER_ID),
 FOREIGN KEY (THREAD_ID) REFERENCES COOLER_THREADS(ID) ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY (USER_ID) REFERENCES USERDATA(ID)
);
 