CREATE TABLE COOLER_POSTS (
 THREAD_ID                  INTEGER UNSIGNED NOT NULL,
 POST_ID                    INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 AUTHOR_ID                  INTEGER UNSIGNED NOT NULL,
 CREATED                    DATETIME NOT NULL,
 REMOTE_ADDR                INTEGER UNSIGNED,
 REMOTE_HOST                VARCHAR(128),
 MSGBODY                    TEXT CHARACTER SET utf8,
 CONTENTWARN				BOOLEAN DEFAULT 0,
 PRIMARY KEY (POST_ID, THREAD_ID),
 FOREIGN KEY (THREAD_ID) REFERENCES COOLER_THREADS(ID) ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY (AUTHOR_ID) REFERENCES USERDATA(ID)
);

CREATE INDEX MSG_BODY_IDX ON COOLER_POSTS(MSGBODY(1000));