CREATE TABLE COOLER_POLLS (
 ID					INTEGER UNSIGNED NOT NULL,
 OPT_ID			TINYINT UNSIGNED NOT NULL,
 NAME				VARCHAR(64) NOT NULL,
 PRIMARY KEY (OPT_ID, ID),
 CONSTRAINT UNIQUE (ID, NAME),
 FOREIGN KEY (ID) REFERENCES COOLER_THREADS(ID) ON DELETE CASCADE
);
