CREATE TABLE COOLER_VIEWS (
 THREAD_ID				INTEGER UNSIGNED NOT NULL,
 VIEWEDON				TIMESTAMP,
 VIEWCOUNT				INTEGER NOT NULL DEFAULT 1,
 PRIMARY KEY (THREAD_ID, VIEWEDON),
 FOREIGN KEY (THREAD_ID) REFERENCES COOLER_THREADS(ID) ON DELETE CASCADE
);

CREATE INDEX CVIEW_VCIDX ON COOLER_VIEWS(VIEWCOUNT);