CREATE TABLE TRACKS (
 ID						INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 USER_ID				INTEGER UNSIGNED NOT NULL,
 NETWORK				VARCHAR(10) NOT NULL,
 CREATED_ON				DATETIME NOT NULL,
 AIRPORT_D				CHAR(4) NOT NULL,
 AIRPORT_A				CHAR(4) NOT NULL,
 ROUTE					MEDIUMTEXT,
 PRIMARY KEY (ID),
 FOREIGN KEY (USER_ID) REFERENCES common.USERDATA(ID) ON UPDATE CASCADE ON DELETE CASCADE
);