CREATE TABLE TRACKDATA (
 ID						INTEGER UNSIGNED NOT NULL,
 REPORT_TIME			DATETIME NOT NULL,
 LAT					DECIMAL (9,4) NOT NULL,
 LNG					DECIMAL (9,4) NOT NULL,
 ALT					INTEGER NOT NULL,
 HDG					SMALLINT UNSIGNED NOT NULL,
 SPEED					SMALLINT NOT NULL,
 PRIMARY KEY (ID, REPORT_TIME),
 FOREIGN KEY (ID) REFERENCES TRACKS(ID) ON UPDATE CASCADE ON DELETE CASCADE
);