CREATE TABLE TRACK_PULLS (
 NETWORK             VARCHAR(10) NOT NULL,
 PULLTIME            DATETIME NOT NULL,
 PRIMARY KEY (NETWORK, PULLTIME)
) DEFAULT CHARSET=latin1;

CREATE INDEX TRACKPULL_DT_IDX ON TRACK_PULLS(PULLTIME);