// Copyright 2022 Global Virtual Airlines Group. All Rights Reserved.
package org.deltava.beans.flight;

import java.time.Instant;

import org.deltava.beans.DatabaseBean;

/**
 * A bean to store a SimBrief briefing package.
 * @author Luke
 * @version 10.3
 * @since 10.3
 */

public class SimBrief extends DatabaseBean {

	private String _sbID;
	private Instant _createdOn;
	
	private int _airac;
	private String _url;
	private String _route;
	
	private String _rwyD;
	private String _rwyA;
	
	private String _xml;

	/**
	 * Creates the bean.
	 * @param id the Flight Report database ID
	 */
	public SimBrief(int id) {
		super();
		setID(id);
	}

	/**
	 * Returns the SimBrief ID for this package.
	 * @return the static ID
	 */
	public String getSimBriefID() {
		return _sbID;
	}

	/**
	 * Returns the generation date of this package.
	 * @return the date/time the package was generated by SimBrief
	 */
	public Instant getCreatedOn() {
		return _createdOn;
	}
	
	/**
	 * Returns the AIRAC version used for this route.
	 * @return the AIRAC version
	 */
	public int getAIRAC() {
		return _airac;
	}

	/**
	 * Returns the flight route.
	 * @return the flight route
	 */
	public String getRoute() {
		return _route;
	}
	
	/**
	 * Returns the departure Runway.
	 * @return the departure runway name
	 */
	public String getRunwayD() {
		return _rwyD;
	}
	
	/**
	 * Returns the arrival Runway.
	 * @return the arrival runway name
	 */
	public String getRunwayA() {
		return _rwyA;
	}
	
	/**
	 * Returns the URL used to download the SimBrief package.
	 * @return the SimBrief URL
	 */
	public String getURL() {
		return _url;
	}
	
	/**
	 * Returns the raw XML generated by SimBrief.
	 * @return the XML
	 */
	public String getXML() {
		return _xml;
	}
	
	/**
	 * Updates the generation date of this package.
	 * @param dt the date/time the package was generated by SimBrief
	 */
	public void setCreatedOn(Instant dt) {
		_createdOn = dt;
	}
	
	/**
	 * Updates the SimBrief plan ID.
	 * @param id the SimBrief ID
	 */
	public void setSimBriefID(String id) {
		_sbID = id;
	}
	
	/**
	 * Updates the AIRAC version used for this route.
	 * @param airac the AIRAC version
	 */
	public void setAIRAC(int airac) {
		_airac = airac;
	}
	
	/**
	 * Updates the flight route.
	 * @param rt the route
	 */
	public void setRoute(String rt) {
		_route = rt;
	}
	
	/**
	 * Updates the departure Runway.
	 * @param rwy the departure runway name
	 */
	public void setRunwayD(String rwy) {
		_rwyD = rwy;
	}
	
	/**
	 * Updates the arrival Runway.
	 * @param rwy the arrival runway name
	 */
	public void setRunwayA(String rwy) {
		_rwyA = rwy;
	}
	
	/**
	 * Updates the URL used to download the briefing package.
	 * @param url the SimBrief URL
	 */
	public void setURL(String url) {
		_url = url;
	}
	
	/**
	 * Updates the raw XML generated by SimBrief.
	 * @param xml the XML
	 */
	public void setXML(String xml) {
		_xml = xml;
	}
}