CREATE OR REPLACE VIEW EQSTAGES AS 
(SELECT ER.RATED_EQ, ER.EQTYPE, MAX(IFNULL(EP.STAGE,1)) AS STAGE 
FROM EQRATINGS ER LEFT JOIN common.EQPROGRAMS EP ON ((ER.EQTYPE=EP.EQTYPE) AND (EP.OWNER=DATABASE())) 
WHERE (ER.RATING_TYPE=1) GROUP BY ER.RATED_EQ);