CREATE TABLE EQAIRLINES (
 EQTYPE					VARCHAR(15) NOT NULL,
 OWNER					CHAR(3) NOT NULL,
 AIRLINE				CHAR(3) NOT NULL,
 PRIMARY KEY (EQTYPE, OWNER, AIRLINE),
 FOREIGN KEY (EQTYPE, OWNER) REFERENCES EQPROGRAMS(EQTYPE, OWNER) ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY (AIRLINE) REFERENCES AIRLINEINFO(CODE) ON DELETE CASCADE ON UPDATE CASCADE
);