CREATE OR REPLACE ALGORITHM = TEMPTABLE DEFINER = CURRENT_USER VIEW EQSTAGES AS 
(SELECT ER.RATED_EQ, ER.EQTYPE, MAX(IFNULL(EP.STAGE,1)) AS MAXSTAGE, ER.RATING_TYPE 
FROM EQRATINGS ER LEFT JOIN common.EQPROGRAMS EP ON ((ER.EQTYPE=EP.EQTYPE) AND (EP.OWNER=DATABASE()) AND (EP.STAGE>1)) 
GROUP BY ER.RATED_EQ;