CREATE TABLE EXAMINFO (
 NAME               VARCHAR(32) NOT NULL,
 STAGE              SMALLINT UNSIGNED NOT NULL,
 MIN_STAGE			SMALLINT UNSIGNED NOT NULL,
 EQTYPE				VARCHAR(15),
 QUESTIONS          SMALLINT UNSIGNED NOT NULL,
 PASS_SCORE         SMALLINT UNSIGNED,
 TIME               SMALLINT UNSIGNED NOT NULL,
 ACTIVE             BOOL,
 REQUIRES_RIDE      BOOL,
 PRIMARY KEY (NAME)
);

CREATE INDEX EXINF_ST_IDX ON EXAMINFO(STAGE);
CREATE INDEX EXINF_MST_IDX ON EXAMINFO(MIN_STAGE);
