CREATE TABLE QUESTIONSTATS (
 ID				INTEGER UNSIGNED NOT NULL,
 ACADEMY		BOOLEAN NOT NULL DEFAULT FALSE,
 TOTAL			INTEGER UNSIGNED NOT NULL DEFAULT 0,
 CORRECT		INTEGER UNSIGNED NOT NULL DEFAULT 0,
 PRIMARY KEY (ID, ACADEMY),
 FOREIGN KEY (ID) REFERENCES QUESTIONINFO(ID) ON UPDATE CASCADE ON DELETE CASCADE
)