CREATE TABLE EXAMQUESTIONS (
 EXAM_ID            	INTEGER UNSIGNED NOT NULL,
 QUESTION_ID        	INTEGER UNSIGNED NOT NULL,
 QUESTION_NO        	SMALLINT NOT NULL,
 QUESTION				VARCHAR(192) NOT NULL,
 CORRECT_ANSWER     	VARCHAR(192) NOT NULL,
 ANSWER             	VARCHAR(192),
 CORRECT            	BOOL,
 PRIMARY KEY (EXAM_ID, QUESTION_NO),
 FOREIGN KEY (EXAM_ID) REFERENCES EXAMS(ID) ON DELETE CASCADE,
 FOREIGN KEY (QUESTION_ID) REFERENCES QUESTIONINFO(ID)
);

CREATE INDEX EQ_SC_IDX ON EXAMQUESTIONS(CORRECT);
CREATE INDEX EQ_NUM_IDX ON EXAMQUESTIONS(QUESTION_ID);