CREATE TABLE APPQUESTIONSM (
 EXAM_ID            	INTEGER UNSIGNED NOT NULL,
 QUESTION_ID        	INTEGER UNSIGNED NOT NULL,
 SEQ					TINYINT UNSIGNED NOT NULL,
 ANSWER					VARCHAR(255) NOT NULL,
 PRIMARY KEY (EXAM_ID, QUESTION_ID, SEQ),
 FOREIGN KEY (EXAM_ID) REFERENCES APPEXAMS(ID) ON DELETE CASCADE,
 FOREIGN KEY (QUESTION_ID) REFERENCES QUESTIONINFO(ID)
);