CREATE TABLE EXAMS (
 ID                 INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 NAME               VARCHAR(32) NOT NULL,
 PILOT_ID           INTEGER UNSIGNED NOT NULL,
 STATUS             SMALLINT,
 CREATED_ON         DATETIME NOT NULL,
 EXPIRY_TIME        DATETIME NOT NULL,
 SUBMITTED_ON       DATETIME,
 GRADED_ON          DATETIME,
 GRADED_BY          INTEGER UNSIGNED,
 PASS               BOOL,
 PRIMARY KEY (ID),
 FOREIGN KEY (NAME) REFERENCES EXAMINFO(NAME) ON UPDATE CASCADE,
 FOREIGN KEY (PILOT_ID) REFERENCES PILOTS(ID) ON DELETE CASCADE
);

CREATE INDEX EX_NM_IDX ON EXAMS(NAME);