CREATE TABLE CHECKRIDE_FLIGHTS (
 ID						INTEGER UNSIGNED NOT NULL,
 ACARS_ID			INTEGER UNSIGNED NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES CHECKRIDES(ID) ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY (ACARS_ID) REFERENCES acars.FLIGHTS(ID) ON UPDATE CASCADE
);