CREATE TABLE EXAMSCORERS (
 NAME               VARCHAR(32) NOT NULL,
 PILOT_ID           INTEGER UNSIGNED NOT NULL,
 PRIMARY KEY (NAME, PILOT_ID),
 FOREIGN KEY (NAME) REFERENCES EXAMINFO(NAME) ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY (PILOT_ID) REFERENCES common.USERDATA(ID) ON UPDATE CASCADE ON DELETE CASCADE
);
