CREATE TABLE QUESTIONINFO (
 ID             	INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 QUESTION       	VARCHAR(255) NOT NULL,
 CORRECT        	VARCHAR(255) NOT NULL,
 ACTIVE         	BOOL,
 PRIMARY KEY (ID)
);

CREATE INDEX QUINF_AC_IDX ON QUESTIONINFO(ACTIVE);