CREATE TABLE QE_INFO (
 EXAM_NAME              VARCHAR(32) NOT NULL,
 QUESTION_ID            INTEGER UNSIGNED NOT NULL,
 PRIMARY KEY (EXAM_NAME, QUESTION_ID),
 FOREIGN KEY (EXAM_NAME) REFERENCES EXAMINFO(NAME) ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY (QUESTION_ID) REFERENCES QUESTIONINFO(ID) ON DELETE CASCADE
);