CREATE TABLE QUESTIONAIRLINES (
 ID						INTEGER UNSIGNED NOT NULL,
 AIRLINE				VARCHAR(3) NOT NULL,
 PRIMARY KEY (ID, AIRLINE),
 FOREIGN KEY (ID) REFERENCES QUESTIONINFO(ID) ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY (AIRLINE) REFERENCES common.AIRLINEINFO(CODE) ON UPDATE CASCADE
);