CREATE TABLE EXAMQUESTIONSRP (
 EXAM_ID            	INTEGER UNSIGNED NOT NULL,
 QUESTION_ID          	INTEGER UNSIGNED NOT NULL,
 AIRPORT_D				CHAR(3) NOT NULL,
 AIRPORT_A				CHAR(4) NOT NULL,
 PRIMARY KEY (EXAM_ID, QUESTION_ID),
 FOREIGN KEY (EXAM_ID, QUESTION_ID) REFERENCES EXAMS(EXAM_ID, QUESTION_ID) ON DELETE CASCADE,
 FOREIGN KEY (AIRPORT_D) REFERENCES common.AIRPORTS(IATA) ON UPDATE CASCADE,
 FOREIGN KEY (AIRPORT_A) REFERENCES common.AIRPORTS(IATA) ON UPDATE CASCADE
);