CREATE TABLE EXAM_AIRLINES (
 NAME               VARCHAR(32) NOT NULL,
 AIRLINE			VARCHAR(3) NOT NULL,
 PRIMARY KEY (NAME, AIRLINE),
 FOREIGN KEY (NAME) REFERENCES EXAMINFO(NAME) ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY (AIRLINE) REFERENCES common.AIRLINEINFO(CODE) ON UPDATE CASCADE ON DELETE CASCADE
);