CREATE TABLE QUESTIONRPINFO (
 ID             		INTEGER UNSIGNED NOT NULL,
 AIRPORT_D				CHAR(3) NOT NULL,
 AIRPORT_A				CHAR(4) NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES QUESTIONINFO(ID) ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY (AIRPORT_D) REFERENCES common.AIRPORTS(IATA) ON UPDATE CASCADE,
 FOREIGN KEY (AIRPORT_A) REFERENCES common.AIRPORTS(IATA) ON UPDATE CASCADE
);