CREATE TABLE CHECKRIDES (
 ID						INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 NAME               	VARCHAR(32) NOT NULL,
 FILENAME				VARCHAR(32),
 PILOT_ID           	INTEGER UNSIGNED NOT NULL,
 STATUS             	SMALLINT UNSIGNED,
 STAGE					SMALLINT UNSIGNED NOT NULL,
 CREATED	         	TIMESTAMP NOT NULL,
 SUBMITTED				TIMESTAMP,
 GRADED		          	TIMESTAMP,
 GRADED_BY          	INTEGER UNSIGNED NOT NULL,
 PASS               	BOOL,
 COMMENTS				TEXT,
 SIZE					INTEGER UNSIGNED,
 PRIMARY KEY(ID),
 FOREIGN KEY (PILOT_ID) REFERENCES PILOT(ID),
 FOREIGN KEY (GRADED_BY) REFERENCES PILOT(ID),
);

CREATE INDEX VIDEO_ST_IDX ON VIDEOS(STATUS);
