CREATE TABLE QUESTIONINFO (
 ID             	INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 QUESTION       	TEXT CHARACTER SET utf8mb4 NOT NULL,
 CORRECT        	TEXT CHARACTER SET utf8mb4 NOT NULL,
 REFERENCE          TEXT CHARACTER SET utf8mb4,
 ACTIVE         	BOOLEAN NOT NULL DEFAULT FALSE,
 AIRLINE			VARCHAR(3) NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (AIRLINE) REFERENCES common.AIRLINEINFO(CODE) ON UPDATE CASCADE
) ROW_FORMAT=Dynamic;