CREATE TABLE CHECKRIDES (
 ID						INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 NAME               	VARCHAR(32) NOT NULL,
 PILOT_ID           	INTEGER UNSIGNED NOT NULL,
 ACARS_ID				INTEGER UNSIGNED,
 STATUS             	SMALLINT,
 CREATED	         	DATETIME NOT NULL,
 SUBMITTED				DATETIME,
 GRADED		          	DATETIME,
 GRADED_BY          	INTEGER UNSIGNED,
 PASS               	BOOL,
 COMMENTS				TEXT,
 EQTYPE					VARCHAR(15) NOT NULL,
 ACTYPE					VARCHAR(15) NOT NULL,
 ACADEMY				BOOL DEFAULT 0,
 PRIMARY KEY(ID),
 FOREIGN KEY (PILOT_ID) REFERENCES PILOTS(ID) ON UPDATE CASCADE,
 FOREIGN KEY (EQTYPE) REFERENCES EQTYPES(EQTYPE) ON UPDATE CASCADE
);

CREATE INDEX CRIDE_PID_IDX ON CHECKRIDES(PILOT_ID);
CREATE INDEX CRIDE_ST_IDX ON CHECKRIDES(STATUS);
