CREATE TABLE CR_DESCS (
 EQTYPE				VARCHAR(16) NOT NULL,
 EQPROGRAM			VARCHAR(15) NOT NULL,
 BODY				TEXT NOT NULL,
 PRIMARY KEY (EQTYPE),
 FOREIGN KEY (EQPROGRAM) REFERENCES EQTYPES(EQTYPE) ON UPDATE CASCADE
);