CREATE TABLE EXAMQUESTIONS (
 EXAM_ID            	INTEGER UNSIGNED NOT NULL,
 QUESTION_ID        	INTEGER UNSIGNED NOT NULL,
 QUESTION_NO        	SMALLINT NOT NULL,
 QUESTION				VARCHAR(255) NOT NULL,
 CORRECT_ANSWER     	VARCHAR(255) NOT NULL,
 ANSWER             	TEXT,
 CORRECT            	BOOLEAN NOT NULL DEFAULT FALSE,
 PRIMARY KEY (EXAM_ID, QUESTION_NO),
 FOREIGN KEY (EXAM_ID) REFERENCES EXAMS(ID) ON DELETE CASCADE,
 FOREIGN KEY (QUESTION_ID) REFERENCES QUESTIONINFO(ID)
);

CREATE INDEX EQ_NUM_IDX ON EXAMQUESTIONS(QUESTION_ID);
