CREATE TABLE QUESTIONMINFO (
 ID             	INTEGER UNSIGNED NOT NULL,
 SEQ				TINYINT UNSIGNED NOT NULL,
 ANSWER				VARCHAR(255) NOT NULL,
 PRIMARY KEY (ID, SEQ),
 FOREIGN KEY (ID) REFERENCES QUESTIONINFO(ID) ON DELETE CASCADE ON UPDATE CASCADE
);