CREATE TABLE EXAMQANSWERS (
 EXAM_ID            	INTEGER UNSIGNED NOT NULL,
 QUESTION_NO        	SMALLINT NOT NULL,
 QUESTION				TEXT NOT NULL,
 CORRECT_ANSWER     	TEXT NOT NULL,
 ANSWER             	TEXT,
 PRIMARY KEY (EXAM_ID, QUESTION_NO),
 FOREIGN KEY (EXAM_ID, QUESTION_NO) REFERENCES EXAMQUESTIONS(EXAM_ID, QUESTION_NO) ON DELETE CASCADE ON UPDATE CASCADE,
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
