CREATE TABLE EXAMINFO (
 NAME               VARCHAR(32) NOT NULL,
 STAGE              SMALLINT NOT NULL,
 MIN_STAGE			SMALLINT NOT NULL,
 EQTYPE				VARCHAR(15),
 QUESTIONS          SMALLINT NOT NULL,
 PASS_SCORE         SMALLINT,
 TIME               SMALLINT NOT NULL,
 ACTIVE             BOOLEAN,
 ACADEMY			BOOLEAN DEFAULT 0,
 AIRLINE			VARCHAR(3) NOT NULL,
 PRIMARY KEY (NAME),
 FOREIGN KEY (AIRLINE) REFERENCES common.AIRLINEINFO(CODE) ON UPDATE CASCADE
);

CREATE INDEX EXINF_ST_IDX ON EXAMINFO(STAGE);
CREATE INDEX EXINF_MST_IDX ON EXAMINFO(MIN_STAGE);
