CREATE TABLE APPQUESTIONS (
 EXAM_ID            	INTEGER UNSIGNED NOT NULL,
 QUESTION_ID        	INTEGER UNSIGNED NOT NULL,
 QUESTION_NO        	SMALLINT NOT NULL,
 QUESTION				TEXT CHARACTER SET utf8mb4 NOT NULL,
 CORRECT_ANSWER     	TEXT CHARACTER SET utf8mb4 NOT NULL,
 ANSWER             	TEXT CHARACTER SET utf8mb4,
 CORRECT            	BOOL,
 PRIMARY KEY (EXAM_ID, QUESTION_NO),
 FOREIGN KEY (EXAM_ID) REFERENCES APPEXAMS(ID) ON DELETE CASCADE,
 FOREIGN KEY (QUESTION_ID) REFERENCES QUESTIONINFO(ID)
);