CREATE TABLE CR_SIMS (
 EQTYPE             VARCHAR(16) NOT NULL,
 EQPROGRAM          VARCHAR(15) NOT NULL,
 CURRENCY           BOOLEAN NOT NULL DEFAULT FALSE,
 SIM                VARCHAR(8) NOT NULL,
 PRIMARY KEY (EQPROGRAM, EQTYPE, CURRENCY, SIM),
 FOREIGN KEY (EQTYPE, EQPROGRAM, CURRENCY) REFERENCES CR_DESCS(EQTYPE, EQPROGRAM, CURRENCY) ON UPDATE CASCADE ON DELETE CASCADE
) CHARACTER SET latin1;