CREATE TABLE CR_DESCS (
 EQTYPE				VARCHAR(16) NOT NULL,
 EQPROGRAM			VARCHAR(15) NOT NULL,
 CURRENCY			BOOLEAN NOT NULL DEFAULT FALSE,
 BODY				TEXT CHARACTER SET utf8 NOT NULL,
 PRIMARY KEY (EQTYPE, CURRENCY),
 FOREIGN KEY (EQPROGRAM) REFERENCES EQTYPES(EQTYPE) ON UPDATE CASCADE,
 FOREIGN KEY (EQTYPE) REFERENCES common.AIRCRAFT(NAME) ON UPDATE CASCADE
);