CREATE TABLE EXAMS (
 ID                 INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 NAME               VARCHAR(32) NOT NULL,
 PILOT_ID           INTEGER UNSIGNED NOT NULL,
 STATUS             SMALLINT,
 CREATED_ON         DATETIME NOT NULL,
 EXPIRY_TIME        DATETIME NOT NULL,
 SUBMITTED_ON       DATETIME,
 GRADED_ON          DATETIME,
 GRADED_BY          INTEGER UNSIGNED,
 PASS               BOOLEAN,
 ISEMPTY			BOOLEAN DEFAULT 0,
 AUTOSCORE			BOOLEAN DEFAULT 0,
 COMMENTS			TEXT,
 PRIMARY KEY (ID),
 FOREIGN KEY (NAME) REFERENCES EXAMINFO(NAME) ON UPDATE CASCADE,
 FOREIGN KEY (PILOT_ID) REFERENCES common.USERDATA(ID) ON DELETE CASCADE
);

CREATE INDEX EX_DT_IDX ON EXAMS(CREATED_ON);
