CREATE TABLE APPEXAMS (
 ID                 INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 APP_ID				INTEGER UNSIGNED NOT NULL,
 STATUS             SMALLINT,
 CREATED_ON         DATETIME NOT NULL,
 EXPIRY_TIME        DATETIME NOT NULL,
 SUBMITTED_ON       DATETIME,
 GRADED_ON          DATETIME,
 GRADED_BY          INTEGER UNSIGNED,
 AUTOSCORE		BOOLEAN DEFAULT 0,
 COMMENTS			TEXT,
 PRIMARY KEY (ID),
 FOREIGN KEY (APP_ID) REFERENCES APPLICANTS(ID) ON DELETE CASCADE
);
