CREATE TABLE CHECKRIDES (
 ID						INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 NAME               	VARCHAR(32) NOT NULL,
 PILOT_ID           	INTEGER UNSIGNED NOT NULL,
 STATUS             	SMALLINT UNSIGNED,
 CREATED_ON         	DATETIME NOT NULL,
 GRADED_ON          	DATETIME,
 GRADED_BY          	INTEGER UNSIGNED,
 PASS               	BOOL,
 COMMENTS				TEXT,
 VIDEO					BOOL,
 SIZE					INTEGER UNSIGNED,
 DATA					MEDIUMBLOB,
 PRIMARY KEY(ID),
 FOREIGN KEY (PILOT_ID) REFERENCES PILOTS(ID)
);

CREATE INDEX VIDEO_PID_IDX ON VIDEOS(PILOT_ID);
CREATE INDEX VIDEO_ST_IDX ON VIDEOS(STATUS);