CREATE TABLE APPQUESTIONS (
 EXAM_ID            	INTEGER UNSIGNED NOT NULL,
 QUESTION_ID        	INTEGER UNSIGNED NOT NULL,
 QUESTION_NO        	SMALLINT NOT NULL,
 QUESTION				VARCHAR(255) NOT NULL,
 CORRECT_ANSWER     	VARCHAR(255) NOT NULL,
 ANSWER             	TEXT,
 CORRECT            	BOOL,
 PRIMARY KEY (EXAM_ID, QUESTION_NO),
 FOREIGN KEY (EXAM_ID) REFERENCES APPEXAMS(ID) ON DELETE CASCADE,
 FOREIGN KEY (QUESTION_ID) REFERENCES QUESTIONINFO(ID)
);

CREATE INDEX AQ_SC_IDX ON APPQUESTIONS(CORRECT);
CREATE INDEX AQ_NUM_IDX ON APPQUESTIONS(QUESTION_ID);