CREATE TABLE EXAMINFO (
 NAME               VARCHAR(32) NOT NULL,
 STAGE              SMALLINT NOT NULL,
 MIN_STAGE			SMALLINT NOT NULL,
 EQTYPE				VARCHAR(15),
 QUESTIONS          SMALLINT NOT NULL,
 PASS_SCORE         SMALLINT NOT NULL,
 TIME               SMALLINT NOT NULL,
 ACTIVE             BOOLEAN NOT NULL DEFAULT 0,
 ACADEMY			BOOLEAN NOT NULL DEFAULT 0,
 AIRLINE			VARCHAR(3) NOT NULL,
 PRIMARY KEY (NAME),
 FOREIGN KEY (AIRLINE) REFERENCES common.AIRLINEINFO(CODE) ON UPDATE CASCADE
);
