CREATE TABLE QUESTIONINFO (
 ID             	INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 QUESTION       	VARCHAR(255) NOT NULL,
 CORRECT        	VARCHAR(255) NOT NULL,
 ACTIVE         	BOOLEAN NOT NULL DEFAULT FALSE,
 AIRLINE			VARCHAR(3) NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (AIRLINE) REFERENCES common.AIRLINEINFO(CODE) ON UPDATE CASCADE
);
