CREATE TABLE QUESTIONIMGS (
 ID             	INTEGER UNSIGNED NOT NULL,
 TYPE           	SMALLINT,
 X              	SMALLINT UNSIGNED NOT NULL,
 Y              	SMALLINT UNSIGNED NOT NULL,
 SIZE           	INTEGER UNSIGNED NOT NULL,
 IMG            	MEDIUMBLOB NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES QUESTIONINFO(ID) ON UPDATE CASCADE ON DELETE CASCADE
);
  