CREATE TABLE EXAM_QPOOLS (
 NAME               VARCHAR(32) NOT NULL,
 ID					INTEGER UNSIGNED NOT NULL DEFAULT 1,
 SUBPOOL			VARCHAR(24) NOT NULL,
 SIZE				SMALLINT UNSIGNED NOT NULL,
 PRIMARY KEY (NAME, ID),
 FOREIGN KEY (NAME) REFERENCES EXAMINFO(NAME) ON UPDATE CASCADE ON DELETE CASCADE
);
