CREATE TABLE CR_DESCS (
 EQTYPE				VARCHAR(16) NOT NULL,
 EQPROGRAM			VARCHAR(15) NOT NULL,
 CURRENCY			BOOLEAN NOT NULL DEFAULT FALSE,
 SIMS				VARCHAR(32) NOT NULL,
 BODY				TEXT CHARACTER SET utf8mb4 NOT NULL,
 PRIMARY KEY (EQPROGRAM, EQTYPE, CURRENCY),
 FOREIGN KEY (EQPROGRAM) REFERENCES EQTYPES(EQTYPE) ON UPDATE CASCADE,
 FOREIGN KEY (EQTYPE) REFERENCES common.AIRCRAFT(NAME) ON UPDATE CASCADE
) ROW_FORMAT=Dynamic;