CREATE TABLE AIRLINES (
 ID					INTEGER UNSIGNED NOT NULL
 AIRLINE			VARCHAR(3) NOT NULL,
 PRIMARY KEY (ID, AIRLINE),
 FOREIGN KEY (ID) REFERENCES EVENTS(ID) ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY (AIRLINE) REFERENCES common.AIRLINEINFO(CODE) ON DELETE CASCADE ON UPDATE CASCADE
);
