CREATE TABLE EVENT_PLANS (
 ID				INTEGER UNSIGNED NOT NULL,
 PLANTYPE		SMALLINT,
 AIRPORT_D		CHAR(3) NOT NULL,
 AIRPORT_A		CHAR(3) NOT NULL,
 PLANDATA		BLOB NOT NULL,
 PRIMARY KEY (ID, PLANTYPE, AIRPORT_D, AIRPORT_A),
 FOREIGN KEY (ID) REFERENCES EVENTS(ID) ON DELETE CASCADE,
 FOREIGN KEY (AIRPORT_D) REFERENCES common.AIRPORTS(IATA),
 FOREIGN KEY (AIRPORT_A) REFERENCES common.AIRPORTS(IATA)
);