CREATE TABLE EVENT_PLANS (
 ID				INTEGER UNSIGNED NOT NULL,
 ROUTE_ID		INTEGER UNSIGNED NOT NULL,
 PLANTYPE		SMALLINT NOT NULL,
 PLANDATA		BLOB NOT NULL,
 PRIMARY KEY (ID, ROUTE_ID, PLANTYPE),
 FOREIGN KEY (ID, ROUTE_ID) REFERENCES EVENT_AIRPORTS(ID, ROUTE_ID) ON DELETE CASCADE,
);