CREATE TABLE AIRPORTS (
 ID                 INTEGER UNSIGNED NOT NULL,
 AIRPORT            CHAR(3) NOT NULL,
 PRIMARY KEY (ID, AIRPORT), 
 FOREIGN KEY (ID) REFERENCES EVENTS(ID) ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY (AIRPORT) REFERENCES common.AIRPORTS(IATA) ON UPDATE CASCADE
) CHARACTER SET latin1;