CREATE TABLE IF NOT EXISTS EVENT_SIGNUPS (
 ID				INTEGER UNSIGNED NOT NULL,
 PILOT_ID		INTEGER UNSIGNED NOT NULL,
 ROUTE_ID	INTEGER UNSIGNED NOT NULL,
 EQTYPE			VARCHAR(12) NOT NULL,
 AIRPORT_D		CHAR(3) NOT NULL,
 AIRPORT_A		CHAR(3) NOT NULL,
 REMARKS		VARCHAR(192),
 PRIMARY KEY (ID, PILOT_ID),
 FOREIGN KEY (ID) REFERENCES EVENTS(ID) ON DELETE CASCADE,
 FOREIGN KEY (ID, ROUTE_ID) REFERENCES EVENT_AIRPORTS(ID, ROUTE_ID) ON DELETE CASCADE,
 FOREIGN KEY (PILOT_ID) REFERENCES common.USERDATA(ID) ON DELETE CASCADE,
 FOREIGN KEY (AIRPORT_D) REFERENCES common.AIRPORTS(IATA),
 FOREIGN KEY (AIRPORT_A) REFERENCES common.AIRPORTS(IATA)
);