CREATE TABLE EVENTS (
 ID				INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 TITLE			VARCHAR(80) CHARACTER SET utf8mb4 NOT NULL,
 STATUS			SMALLINT NOT NULL,
 NETWORK		SMALLINT,
 STARTTIME		DATETIME NOT NULL,
 ENDTIME		DATETIME NOT NULL,
 SU_DEADLINE	DATETIME NOT NULL,
 BRIEFING		MEDIUMTEXT CHARACTER SET utf8mb4,
 CAN_SIGNUP		BOOLEAN NOT NULL DEFAULT 1,
 SIGNUP_URL		VARCHAR(224),
 OWNER			VARCHAR(3) NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (OWNER) REFERENCES REFERENCES common.AIRLINEINFO(CODE) ON UPDATE CASCADE
);
