CREATE TABLE EVENT_AIRPORTS (
 ID				INTEGER UNSIGNED NOT NULL,
 ROUTE_ID	INTEGER UNSIGNED NOT NULL,
 AIRPORT_D		CHAR(3) NOT NULL,
 AIRPORT_A		CHAR(3) NOT NULL,
 ROUTE			TEXT,
 ACTIVE			BOOLEAN DEFAULT 1,
 MAX_SIGNUPS	SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 NAME			VARCHAR(160),
 PRIMARY KEY (ID, ROUTE_ID),
 FOREIGN KEY (ID) REFERENCES EVENTS(ID) ON DELETE CASCADE,
 FOREIGN KEY (AIRPORT_D) REFERENCES common.AIRPORTS(IATA),
 FOREIGN KEY (AIRPORT_A) REFERENCES common.AIRPORTS(IATA)
);