CREATE TABLE BRIEFINGS (
 ID                  INTEGER UNSIGNED NOT NULL,
 ISPDF               BOOLEAN NOT NULL DEFAULT FALSE,
 SIZE                INTEGER UNSIGNED NOT NULL DEFAULT 0,
 DATA                MEDIUMBLOB NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES EVENTS(ID) ON DELETE CASCADE
) CHARACTER SET latin1 ROW_FORMAT=DYNAMIC;