CREATE TABLE EVENT_EQTYPES (
 ID				INTEGER UNSIGNED NOT NULL,
 RATING			VARCHAR(16) NOT NULL,
 PRIMARY KEY (ID, RATING),
 FOREIGN KEY (ID) REFERENCES EVENTS(ID) ON DELETE CASCADE,
 FOREIGN KEY (RATING) REFERENCES common.AIRCRAFT(NAME) ON DELETE CASCADE ON UPDATE CASCADE
);