CREATE TABLE BANNERS (
 ID					INTEGER UNSIGNED NOT NULL,
 IMG				MEDIUMBLOB NOT NULL,
 X					SMALLINT UNSIGNED NOT NULL,
 Y					SMALLINT UNSIGNED NOT NULL,
 EXT				CHAR(3) NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES EVENTS(ID) ON DELETE CASCADE
);