CREATE TABLE EVENT_CHARTS (
 ID				INTEGER UNSIGNED NOT NULL,
 CHART			INTEGER UNSIGNED NOT NULL,
 PRIMARY KEY (ID, CHART),
 FOREIGN KEY (ID) REFERENCES EVENTS(ID) ON DELETE CASCADE,
 FOREIGN KEY (CHART) REFERENCES common.CHARTS(ID) ON DELETE CASCADE ON UPDATE CASCADE
);