CREATE TABLE EVENTS (
 ID				INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 TITLE			VARCHAR(80) NOT NULL,
 STATUS			SMALLINT,
 NETWORK		SMALLINT,
 STARTTIME		DATETIME NOT NULL,
 ENDTIME		DATETIME NOT NULL,
 SU_DEADLINE	DATETIME NOT NULL,
 BRIEFING		TEXT,
 CAN_SIGNUP		BOOLEAN NOT NULL DEFAULT 1,
 SIGNUP_URL		VARCHAR(224),
 PRIMARY KEY (ID)
);