CREATE TABLE EVENT_PLANS (
 ID				INTEGER UNSIGNED NOT NULL,
 ROUTE_ID		INTEGER UNSIGNED NOT NULL,
 PLANTYPE		SMALLINT,
 AIRPORT_D		CHAR(3) NOT NULL,
 AIRPORT_A		CHAR(3) NOT NULL,
 PLANDATA		BLOB NOT NULL,
 PRIMARY KEY (ID, ROUTE_ID, PLANTYPE),
 FOREIGN KEY (ID) REFERENCES EVENTS(ID) ON DELETE CASCADE,
 FOREIGN KEY (ID, ROUTE_ID) REFERENCES EVENT_AIRPORTS(ID, ROUTE_ID) ON DELETE CASCADE,
 FOREIGN KEY (AIRPORT_D) REFERENCES common.AIRPORTS(IATA),
 FOREIGN KEY (AIRPORT_A) REFERENCES common.AIRPORTS(IATA)
);