CREATE TABLE EVENTS (
 ID				INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 TITLE			VARCHAR(80) NOT NULL,
 STATUS			SMALLINT,
 NETWORK		SMALLINT,
 STARTTIME		DATETIME NOT NULL,
 ENDTIME		DATETIME NOT NULL,
 SU_DEADLINE	DATETIME NOT NULL,
 ROUTE			TEXT,
 BRIEFING		TEXT,
 LEGACY_ID		VARCHAR(48),
 PRIMARY KEY (ID)
);

CREATE INDEX EV_STATUS_IDX ON EVENTS(STATUS);
CREATE INDEX EV_ST_IDX ON EVENTS(STARTTIME);

 