CREATE TABLE FEEDBACK (
 ID               INTEGER UNSIGNED NOT NULL,
 PILOT_ID         INTEGER UNSIGNED NOT NULL,
 CREATED          DATETIME NOT NULL,
 SCORE            TINYINT UNSIGNED NOT NULL DEFAULT 0,
 COMMENTS         TEXT CHARACTER SET utf8mb4,
 PRIMARY KEY (ID, PILOT_ID),
 FOREIGN KEY (ID) REFERENCES EVENTS(ID) ON UPDATE CASCADE ON DELETE CASCADE, 
 FOREIGN KEY (PILOT_ID) REFERENCES common.USERDATA(ID) ON UPDATE CASCADE ON DELETE CASCADE
) CHARACTER SET latin1;