CREATE TABLE EVENT_AIRPORTS (
 ID				INTEGER UNSIGNED NOT NULL,
 AIRPORT_D		CHAR(3) NOT NULL,
 AIRPORT_A		CHAR(3) NOT NULL,
 ROUTE			TEXT,
 ACTIVE			BOOLEAN DEFAULT 1,
 PRIMARY KEY (ID, AIRPORT_D, AIRPORT_A),
 FOREIGN KEY (ID) REFERENCES EVENTS(ID) ON DELETE CASCADE,
 FOREIGN KEY (AIRPORT_D) REFERENCES AIRPORTS(IATA),
 FOREIGN KEY (AIRPORT_A) REFERENCES AIRPORTS(IATA)
);