CREATE TABLE AUTH (
 ID				INTEGER UNSIGNED NOT NULL,
 PWD			VARCHAR(64) NOT NULL,
 ENABLED		BOOLEAN DEFAULT 1,
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES USERDATA(ID) ON DELETE CASCADE ON UPDATE CASCADE
);