CREATE TABLE ISSUE_COMMENTS (
 ID							INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 ISSUE_ID					INTEGER UNSIGNED NOT NULL,
 AUTHOR						INTEGER UNSIGNED NOT NULL,
 CREATED					DATETIME NOT NULL,
 COMMENTS					TEXT,
 PRIMARY KEY (ID),
 FOREIGN KEY (ISSUE_ID) REFERENCES ISSUES(ID) ON DELETE CASCADE,
 FOREIGN KEY (AUTHOR) REFERENCES USERDATA(ID)
);
