CREATE TABLE LOG_APP (
 ID					INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 CREATED			DATETIME,
 PRIORITY			SMALLINT UNSIGNED,
 LOGGER				VARCHAR(255), 
 MSG				TEXT, 
 ERROR				TEXT,
 PRIMARY KEY(ID)
);

CREATE INDEX LOG_DT_IDX ON LOG_APP(CREATED);
