CREATE TABLE AIRCRAFT_AIRLINE (
 NAME					VARCHAR(15) NOT NULL,
 AIRLINE				CHAR(3) NOT NULL,
 PRIMARY KEY (NAME, AIRLINE),
 FOREIGN KEY (NAME) REFERENCES AIRCRAFT(NAME) ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY (AIRLINE) REFERENCES AIRLINEINFO(CODE) ON DELETE CASCADE ON UPDATE CASCADE
);