CREATE TABLE XDB_IDS (
 ID							INTEGER UNSIGNED NOT NULL,
 OTHER_ID				INTEGER UNSIGNED NOT NULL,
 PRIMARY KEY (ID, OTHER_ID),
 FOREIGN KEY (ID) REFERENCES USERDATA(ID) ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY (OTHER_ID) REFERENCES USERDATA(ID) ON DELETE CASCADE ON UPDATE CASCADE
);