CREATE TABLE MSG_TEMPLATES (
 NAME				VARCHAR(48) NOT NULL,
 SUBJECT			VARCHAR(128) NOT NULL,
 DESCRIPTION		VARCHAR(128) NOT NULL,
 BODY				TEXT NOT NULL,
 ISHTML				BOOL DEFAULT FALSE,
 PRIMARY KEY (NAME)
);