CREATE TABLE SYS_API_USAGE (
 USAGE_DATE             DATETIME(3) NOT NULL,
 API                    VARCHAR(32) NOT NULL,
 USE_COUNT              INTEGER UNSIGNED NOT NULL DEFAULT 0,
 ANONYMOUS              INTEGER UNSIGNED NOT NULL DEFAULT 0,
 BLOCKED                INTEGER UNSIGNED NOT NULL DEFAULT 0,
 PRIMARY KEY (USAGE_DATE, API)
) CHARACTER SET latin1;