CREATE TABLE SYS_SESSIONS (
 ID							VARCHAR(64) NOT NULL,
 PILOT_ID					INTEGER UNSIGNED,
 START_TIME					DATETIME NOT NULL,
 END_TIME					DATETIME,
 REMOTE_ADDR				VARCHAR(16) NOT NULL,
 REMOTE_HOST				VARCHAR(192) NOT NULL,
 PRIMARY KEY (ID)
);

CREATE INDEX SES_ST_IDX ON SYS_SESSIONS(START_TIME);
CREATE INDEX SES_USR_IDX ON SYS_SESSIONS(PILOT_ID);
