CREATE TABLE MSG_TEMPLATES (
 NAME				VARCHAR(48) NOT NULL,
 SUBJECT			VARCHAR(128) CHARACTER SET utf8mb4 NOT NULL,
 DESCRIPTION		VARCHAR(128) CHARACTER SET utf8mb4 NOT NULL,
 PUSHCTX            VARCHAR(32),
 BODY				TEXT CHARACTER SET utf8mb4 NOT NULL,
 ISHTML				BOOLEAN NOT NULL DEFAULT FALSE,
 TTL                INTEGER UNSIGNED NOT NULL, 
 PRIMARY KEY (NAME)
) CHARACTER SET latin1 ROW_FORMAT=Dynamic;