CREATE TABLE AUTH_ROLES (
 ID                     INTEGER UNSIGNED NOT NULL,
 ROLE                   VARCHAR(32) NOT NULL,
 PRIMARY KEY (ID, ROLE),
 FOREIGN KEY (ID) REFERENCES USERDATA(ID) ON DELETE CASCADE ON UPDATE CASCADE
) CHARACTER SET latin1;