CREATE TABLE AUDIT_LOG (
 CREATED                DATETIME NOT NULL,
 TYPE                   VARCHAR(16) NOT NULL,
 ID                     VARCHAR(32) NOT NULL,
 AUTHOR_ID              INTEGER UNSIGNED NOT NULL,
 REMOTE_ADDR            VARBINARY(16),
 REMOTE_HOST            VARCHAR(128),
 DESCRIPTION            TEXT CHARACTER SET utf8 NOT NULL,
 PRIMARY KEY (TYPE, ID, CREATED),
 FOREIGN KEY (AUTHOR_ID) REFERENCES USERDATA(ID) ON UPDATE CASCADE
);