CREATE TABLE SYS_LOGINS (
 ID						INTEGER UNSIGNED NOT NULL,
 REMOTE_ADDR			INTEGER UNSIGNED NOT NULL,
 REMOTE_HOST			VARCHAR(160) NOT NULL,
 LOGINS					INTEGER UNSIGNED NOT NULL DEFAULT 1,
 PRIMARY KEY (ID, REMOTE_ADDR),
 FOREIGN KEY (ID) REFERENCES common.USERDATA(ID) ON UPDATE CASCADE
);