CREATE TABLE ISSUE_COMMENTS (
 ID							INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 ISSUE_ID					INTEGER UNSIGNED NOT NULL,
 AUTHOR						INTEGER UNSIGNED NOT NULL,
 CREATED					TIMESTAMP NOT NULL,
 COMMENTS					TEXT,
 PRIMARY KEY (ID),
 FOREIGN KEY (ISSUE_ID) REFERENCES ISSUES(ID),
 FOREIGN KEY (AUTHOR) REFERENCES PILOTS(ID)
);
