CREATE TABLE INACTIVITY (
 ID					INTEGER UNSIGNED NOT NULL,
 PURGE_DATE			DATE NOT NULL,
 NOTIFY				BOOL,
 PURGE_DAYS		SHORTINT UNSIGNED DEFAULT 0,
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES common.USERDATA(ID) ON DELETE CASCADE
);