CREATE TABLE USERDATA (
 ID					INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 AIRLINE			CHAR(3) NOT NULL,
 DBNAME				VARCHAR(12) NOT NULL,
 TABLENAME			VARCHAR(16) NOT NULL,
 DOMAIN				VARCHAR(32) NOT NULL,
 PRIMARY KEY (ID)
);