CREATE TABLE TABLE_INFO (
 DB              VARCHAR(16) NOT NULL,
 TABLE_NAME      VARCHAR(48) NOT NULL,
 ROW_FORMAT      VARCHAR(16) NOT NULL,
 COMPRESSION     VARCHAR(8) NOT NULL,
 ROW_COUNT       INTEGER UNSIGNED NOT NULL DEFAULT 0,
 LOGICAL_SIZE    INTEGER UNSIGNED NOT NULL DEFAULT 0,
 FILE_SIZE       INTEGER UNSIGNED NOT NULL DEFAULT 0,
 DISK_SIZE       INTEGER UNSIGNED NOT NULL DEFAULT 0,
 PCT_SAVED       DECIMAL(4, 2) DEFAULT 0,
 PRIMARY KEY (DB, TABLE_NAME)
) CHARACTER SET latin1;