CREATE TABLE AIRLINEINFO (
 CODE				VARCHAR(3) NOT NULL,
 NAME				VARCHAR(48) NOT NULL,
 DBNAME				VARCHAR(12) NOT NULL,
 DOMAIN				VARCHAR(32) NOT NULL,
 CAN_TX				BOOL,
 PRIMARY KEY (CODE)
);
