CREATE TABLE ISSUE_FILES (
 ID							INTEGER UNSIGNED NOT NULL,
 SIZE						INTEGER UNSIGNED NOT NULL DEFAULT 0,
 NAME						VARCHAR(64) NOT NULL,
 BODY						MEDIUMBLOB NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES ISSUE_COMMENTS(ID) ON DELETE CASCADE
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;