CREATE TABLE EMAIL_DELIVERY (
 ID                     INTEGER UNSIGNED NOT NULL,
 SEND_TIME              DATETIME NOT NULL,
 RCPT_TIME              DATETIME NOT NULL,
 EMAIL                  VARCHAR(96) NOT NULL,
 PROCESS_TIME           INTEGER UNSIGNED NOT NULL DEFAULT 0,
 REMOTE_ADDR            VARBINARY(16),
 REMOTE_HOST            VARCHAR(128),
 RESPONSE               VARCHAR(144),
 PRIMARY KEY (ID, RCPT_TIME),
 FOREIGN KEY (ID) REFERENCES common.USERDATA(ID) ON UPDATE CASCADE
);