CREATE TABLE USERDATA (
 ID					INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 AIRLINE			CHAR(3) NOT NULL,
 TABLENAME			VARCHAR(16) NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (AIRLINE) REFERENCES AIRLINEINFO(CODE) ON UPDATE CASCADE,
);