CREATE TABLE AUDIT_LOG (
 CREATED                DATETIME NOT NULL,
 TYPE                   VARCHAR(32) NOT NULL,
 ID                     VARCHAR(32) NOT NULL,
 APPNAME                VARCHAR(8) NOT NULL DEFAULT 'COMMON',
 AUTHOR_ID              INTEGER UNSIGNED NOT NULL,
 REMOTE_ADDR            VARBINARY(16),
 REMOTE_HOST            VARCHAR(128),
 DESCRIPTION            TEXT CHARACTER SET utf8mb4 NOT NULL,
 PRIMARY KEY (TYPE, ID, APPNAME, CREATED),
 FOREIGN KEY (AUTHOR_ID) REFERENCES USERDATA(ID) ON UPDATE CASCADE
) ROW_FORMAT=Dynamic;