CREATE TABLE SYS_COMMANDS (
 CMDDATE			DATETIME NOT NULL,
 PILOT_ID			INTEGER UNSIGNED,
 REMOTE_ADDR		INTEGER UNSIGNED NOT NULL,
 REMOTE_HOST		VARCHAR(192) NOT NULL,
 NAME				VARCHAR(24) NOT NULL,
 RESULT				VARCHAR(96),
 TOTAL_TIME			INTEGER UNSIGNED,
 BE_TIME			INTEGER UNSIGNED,
 SUCCESS			BOOL,
 PRIMARY KEY (CMDDATE, REMOTE_ADDR, NAME)
);

CREATE INDEX CMD_ID_IDX ON SYS_COMMANDS(PILOT_ID);
CREATE INDEX CMD_NAME_IDX ON SYS_COMMANDS(NAME);
