CREATE TABLE SYS_HTTPLOG (
 DATE				DATE NOT NULL,
 REQUESTS			INTEGER UNSIGNED NOT NULL DEFAULT 0,
 HOMEHITS			INTEGER UNSIGNED NOT NULL DEFAULT 0,
 EXECTIME			BIGINT UNSIGNED NOT NULL DEFAULT 0,
 BANDWIDTH			BIGINT UNSIGNED NOT NULL DEFAULT 0,
 PRIMARY KEY (DATE)
);