CREATE TABLE SYS_BLACKLIST (
 ADDR                   VARBINARY(16) NOT NULL,
 PREFIXLENGTH           SMALLINT UNSIGNED NOT NULL DEFAULT 32,
 CREATED                DATETIME NOT NULL,
 COMMENTS               TEXT CHARACTER SET utf8mb4,
 PRIMARY KEY (ADDR, PREFIXLENGTH)
) CHARACTER SET latin1;