CREATE TABLE LOG_TASK (
 ID					INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 CREATED			TIMESTAMP,
 PRIORITY			SMALLINT UNSIGNED,
 LOGGER				VARCHAR(255), 
 MSG				TEXT, 
 ERROR				TEXT,
 PRIMARY KEY(ID)
);

CREATE INDEX TASKLOG_DT_IDX ON LOG_TASK(CREATED);
