CREATE TABLE REG_BLOCKS (
 ID							INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 FIRSTNAME					VARCHAR(32),
 LASTNAME					VARCHAR(32),
 REMOTE_ADDR				INTEGER UNSIGNED DEFAULT 0,
 NETMASK					INTEGER UNSIGNED DEFAULT 0xFFFFFF,
 HOSTNAME					VARCHAR(128),
 COMMENTS					VARCHAR(255),
 HAS_FEEDBACK				BOOLEAN DEFAULT 0,
 ACTIVE						BOOLEAN DEFAULT 0,
 PRIMARY KEY(ID)
);