CREATE TABLE SYS_REPORTS (
 ID                    INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 CREATED               DATETIME NOT NULL,
 TYPE                  VARCHAR(16) NOT NULL,
 URL                   VARCHAR(96) NOT NULL,
 BODY                  SMALLTEXT CHARACTER SET utf8mb4 NOT NULL,
 PRIMARY KEY (ID)
) CHARACTER SET Latin1;