CREATE TABLE MSG_TEMPLATES (
 NAME				VARCHAR(48) NOT NULL,
 SUBJECT			VARCHAR(128) CHARACTER SET utf8mb4 NOT NULL,
 DESCRIPTION		VARCHAR(128) CHARACTER SET utf8mb4 NOT NULL,
 BODY				TEXT CHARACTER SET utf8mb4 NOT NULL,
 ISHTML				BOOL NOT NULL DEFAULT FALSE,
 PRIMARY KEY (NAME)
);