CREATE TABLE AUTH (
 ID				INTEGER UNSIGNED NOT NULL,
 PWD			VARCHAR(64) NOT NULL,
 NAME			VARCHAR(64) CHARACTER SET utf8mb4 NOT NULL,
 ENABLED		BOOLEAN NOT NULL DEFAULT TRUE,
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES USERDATA(ID) ON DELETE CASCADE ON UPDATE CASCADE
);