CREATE TABLE ADMIN_LOG (
 CREATED                DATETIME NOT NULL,
 NAME                   VARCHAR(24) NOT NULL,
 ID                     VARCHAR(16) NOT NULL,
 AUTHOR_ID              INTEGER UNSIGNED NOT NULL DEFAULT 0,
 REMOTE_ADDR            VARBINARY(16),
 REMOTE_HOST            VARCHAR(128),
 PRIMARY KEY (CREATED, NAME),
 FOREIGN KEY (AUTHOR_ID) REFERENCES common.USERDATA(ID) ON UPDATE CASCADE
) CHARACTER SET latin1;