// Copyright 2009 Global Virtual Airlines Group. All Rights Reserved.
package org.deltava.util.flightplan;

import java.util.Collection;

import org.deltava.beans.schedule.Airport;
import org.deltava.beans.navdata.NavigationDataBean;

/**
 * An abstract class to describe flight plan generators for simulators and payware aircraft. 
 * @author Luke
 * @version 2.4
 * @since 2.4
 */

public abstract class FlightPlanGenerator {
	
	/**
	 * The departure airport.
	 */
	protected Airport _aD;
	
	/**
	 * The arrivla airport.
	 */
	protected Airport _aA;
	
	/**
	 * The cruise altitude.
	 */
	protected String _altitude;
	
	/**
	 * Sets the departure and arrival Airports for the flight.
	 * @param aD the departure Airport
	 * @param aA the arrival Airport
	 */
	public void setAirports(Airport aD, Airport aA) {
		_aD = aD;
		_aA = aA;
	}
	
	/**
	 * Sets the cruise altitude for the flight.
	 * @param alt the altitude
	 */
	public void setCruiseAltitude(String alt) {
		_altitude = alt;
	}

	/**
	 * Generates a flight plan between two airports.
	 * @param waypoints a Collection of waypoints
	 * @return the generated flight plan file
	 */
	public abstract byte[] generate(Collection<NavigationDataBean> waypoints);
	
	/**
	 * Returns the MIME type of flight plans generated by this Generator.
	 * @return the MIME type
	 */
	public abstract String getMimeType();
	
	/**
	 * Returns the file extension of flight plans generated by this Generator.
	 * @return the file extension
	 */
	public abstract String getExtension();
}