CREATE TABLE TAFS (
 AIRPORT			CHAR(4) NOT NULL,
 DATE				DATETIME NOT NULL,
 AMENDED			BOOLEAN NOT NULL DEFAULT FALSE,
 DATA				TEXT CHARACTER SET utf8mb4 NOT NULL,
 PRIMARY KEY (AIRPORT)
);

CREATE INDEX TAF_DT_IDX ON TAFS(DATE);
