CREATE TABLE METARS (
 AIRPORT			CHAR(4) NOT NULL,
 DATE				DATETIME NOT NULL,
 ILS				SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 LOC                POINT NOT NULL,
 DATA				TEXT CHARACTER SET utf8mb4 NOT NULL,
 PRIMARY KEY (AIRPORT)
);

CREATE SPATIAL INDEX METAR_GEO_IDX ON METARS(LOC);
