CREATE TABLE METARS (
 AIRPORT			CHAR(4) NOT NULL,
 DATE				DATETIME NOT NULL,
 ILS				SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 DATA				VARCHAR(512) NOT NULL,
 PRIMARY KEY (AIRPORT)
);

CREATE INDEX METAR_DT_IDX ON METARS(DATE);
