CREATE TABLE WINDS (
 DATE				DATETIME NOT NULL,
 LAT				DECIMAL(5,2) NOT NULL,
 LNG				DECIMAL(5,2) NOT NULL,
 MB					SMALLINT UNSIGNED NOT NULL,
 ALT				SMALLINT UNSIGNED NOT NULL,
 TMP				SMALLINT NOT NULL DEFAULT 0,
 WSPD				SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 WDIR				SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 PRIMARY KEY (DATE, LAT, LNG, MB)
);