CREATE TABLE WINDS (
 DATE				DATETIME NOT NULL,
 LAT				DECIMAL(5,2) NOT NULL,
 LNG				DECIMAL(5,2) NOT NULL,
 ALT				SMALLINT UNSIGNED NOT NULL,
 WSPD				SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 WDIR				SMALLINT UNSIGNED NOT NULL,
 PRIMARY KEY (DATE, LAT, LNG)
);