CREATE TABLE ACARS_METADATA (
 ID                  INTEGER UNSIGNED NOT NULL,
 AUTHOR              VARCHAR(128) CHARACTER SET utf8mb4,
 ACPATH              VARCHAR(128),
 FDE                 VARCHAR(64),
 CODE                VARCHAR(24),
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES PIREPS(ID) ON DELETE CASCADE ON UPDATE CASCADE
) CHARACTER SET latin1;