CREATE TABLE ONLINE_TRACK (
 PILOT_ID				INTEGER UNSIGNED NOT NULL,
 NETWORK				VARCHAR(7) NOT NULL,
 PIREP_ID				INTEGER UNSIGNED NOT NULL DEFAULT 0,
 DATE					DATETIME NOT NULL,
 AIRPORT_D				CHAR(3) NOT NULL,
 AIRPORT_A				CHAR(3) NOT NULL,
 LAT					DECIMAL (9,4) NOT NULL,
 LNG					DECIMAL (9,4) NOT NULL,
 ALT					INTEGER NOT NULL,
 HEADING				SMALLINT NOT NULL,
 ASPEED					SMALLINT NOT NULL,
 PRIMARY KEY (PILOT_ID, DATE),
 FOREIGN KEY (PILOT_ID) REFERENCES PILOTS(ID) ON UPDATE CASCADE,
 FOREIGN KEY (AIRPORT_D) REFERENCES common.AIRPORTS(IATA) ON UPDATE CASCADE,
 FOREIGN KEY (AIRPORT_A) REFERENCES common.AIRPORTS(IATA) ON UPDATE CASCADE
);
