CREATE TABLE PIREP_SIMBRIEF (
 ID                INTEGER UNSIGNED NOT NULL,
 SIMBRIEF_ID       VARCHAR(24) NOT NULL,
 AIRAC             SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 CREATED           DATETIME NOT NULL,
 RUNWAY_D          VARCHAR(6),
 RUNWAY_A          VARCHAR(6),
 ROUTE             MEDIUMTEXT NOT NULL,
 XML               MEDIUMTEXT CHARACTER SET utf8mb4 NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES PIREPS(ID) ON UPDATE CASCADE ON DELETE CASCADE
) COMPRESSION="LZ4";
