CREATE TABLE PIREP_DRAFT (
 ID                  INTEGER UNSIGNED NOT NULL,
 TIME_D              TIME,
 TIME_A              TIME,
 GATE_D              VARCHAR(16),
 GATE_A              VARCHAR(16),
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES PIREPS(ID) ON UPDATE CASCADE ON DELETE CASCADE
) CHARACTER SET latin1;