CREATE TABLE PIREPS (
 ID					INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 PILOT_ID			INTEGER UNSIGNED NOT NULL,
 RANK				VARCHAR(18) DEFAULT 'First Officer',
 STATUS				SMALLINT,
 DATE				DATE NOT NULL,
 AIRLINE			CHAR(3) NOT NULL,
 FLIGHT				SMALLINT NOT NULL,
 LEG				SMALLINT NOT NULL,
 AIRPORT_D			CHAR(3) NOT NULL,
 AIRPORT_A			CHAR(3) NOT NULL,
 EQTYPE				VARCHAR(15) NOT NULL,
 FSVERSION			SMALLINT,
 ATTR				INTEGER,
 DISTANCE			SMALLINT NOT NULL,
 FLIGHT_TIME		NUMERIC(3,1),
 REMARKS			TEXT,
 DISPOSAL_ID		INTEGER,
 SUBMITTED			DATETIME,
 DISPOSED			DATETIME,
 EVENT_ID			INTEGER,
 ASSIGN_ID			INTEGER,
 PRIMARY KEY (ID),
 FOREIGN KEY (PILOT_ID) REFERENCES PILOTS(ID),
 FOREIGN KEY (AIRLINE) REFERENCES common.AIRLINES(CODE) ON UPDATE CASCADE,
 FOREIGN KEY (AIRPORT_D) REFERENCES common.AIRPORTS(IATA) ON UPDATE CASCADE,
 FOREIGN KEY (AIRPORT_A) REFERENCES common.AIRPORTS(IATA) ON UPDATE CASCADE
);

CREATE INDEX PIREP_EQ_IDX ON PIREPS(EQTYPE);
CREATE INDEX PIREP_ST_IDX ON PIREPS(STATUS);
CREATE INDEX PIREP_DT_IDX ON PIREPS(DATE);
CREATE INDEX PIREP_EV_IDX ON PIREPS(EVENT_ID);
CREATE INDEX PIREP_AS_IDX ON PIREPS(ASSIGN_ID);
CREATE INDEX PIREP_AT_IDX ON PIREPS(ATTR);
