CREATE TABLE PIREP_AGGREGATE_QUEUE (
 ID                 INTEGER UNSIGNED NOT NULL,
 CREATED            DATETIME NOT NULL,
 COMPLETION         BOOLEAN NOT NULL DEFAULT FALSE,
 STATS              BOOLEAN NOT NULL DEFAULT FALSE,
 ELITE              BOOLEAN NOT NULL DEFAULT FALSE,
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES PIREPS(ID) ON DELETE CASCADE ON UPDATE CASCADE
) CHARACTER SET latin1;
