CREATE TABLE ONLINE_TRACK (
 PILOT_ID				INTEGER UNSIGNED NOT NULL,
 PIREP_ID				INTEGER UNSIGNED NOT NULL DEFAULT 0,
 DATE					DATETIME NOT NULL,
 LAT					DECIMAL (9,4) NOT NULL,
 LNG					DECIMAL (9,4) NOT NULL,
 ALT					INTEGER NOT NULL,
 HEADING				SMALLINT NOT NULL,
 ASPEED					SMALLINT NOT NULL,
 PRIMARY KEY (PIREP_ID, DATE),
 FOREIGN KEY (PIREP_ID) REFERENCES PIREPS(ID) ON UPDATE CASCADE ON DELETE CASCADE
);
