CREATE TABLE ACARS_ONTIME (
 ID              INTEGER UNSIGNED NOT NULL,
 ONTIME          TINYINT UNSIGNED NOT NULL DEFAULT 0,
 AIRLINE         CHAR(3) NOT NULL,
 FLIGHT          SMALLINT UNSIGNED NOT NULL,
 LEG             TINYINT UNSIGNED NOT NULL DEFAULT 1,
 TIME_D          DATETIME NOT NULL,
 TIME_A          DATETIME NOT NULL,
 ATIME_D         DATETIME NOT NULL,
 ATIME_A         DATETIME NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES PIREPS(ID) ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY (AIRLINE) REFERENCES common.AIRLINES(CODE) ON UPDATE CASCADE
) DEFAULT CHARSET latin1;