CREATE TABLE PIREP_COMMENT (
 ID					INTEGER UNSIGNED NOT NULL,
 COMMENTS			TEXT CHARACTER SET utf8mb4,
 REMARKS			TEXT CHARACTER SET utf8mb4,
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES PIREPS(ID) ON DELETE CASCADE
) ROW_FORMAT=Dynamic;