CREATE TABLE PIREP_STATUS_HISTORY (
 ID                  INTEGER UNSIGNED NOT NULL,
 AUTHOR_ID           INTEGER UNSIGNED NOT NULL DEFAULT 0,
 CREATEDON           DATETIME(3) NOT NULL,
 DESC                TEXT NOT NULL CHARACTER SET utf8mb4,
 PRIMARY KEY (ID, CREATEDON),
 FOREIGN KEY (ID) REFERENCES PIREPS(ID) ON UPDATE CASCADE ON DELETE CASCADE,
) CHARACTER SET latin1;