CREATE TABLE PIREP_ELITE_ENTRIES (
 ID                   INTEGER UNSIGNED NOT NULL,
 SEQ                  TINYINT UNSIGNED NOT NULL,
 SCORE                SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 BONUS                SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 REMARKS              VARCHAR(160),
 PRIMARY KEY (ID, SEQ),
 FOREIGN KEY (ID) REFERENCES PIREP_ELITE(ID) ON DELETE CASCADE ON UPDATE CASCADE
) CHARACTER SET latin1;