CREATE TABLE PIREP_COMMENT (
 ID					INTEGER UNSIGNED NOT NULL,
 COMMENTS			TEXT CHARACTER SET utf8,
 REMARKS			TEXT CHARACTER SET utf8,
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES PIREPS(ID) ON DELETE CASCADE
);