CREATE TABLE PIREP_AGGREGATE_QUEUE (
 ID                 INTEGER UNSIGNED NOT NULL,
 CREATED            DATETIME NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES PIREPS(ID) ON DELETE CASCADE ON UPDATE CASCADE
) CHARACTER SET latin1;
