CREATE TABLE PIREP_ELITE (
 ID                 INTEGER UNSIGNED NOT NULL,
 YEAR               SMALLINT UNSIGNED NOT NULL,
 LEVEL              VARCHAR(32) NOT NULL,
 DISTANCE           SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 SCORE              SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 SCORE_ONLY         BOOLEAN NOT NULL DEFAULT FALSE,
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES PIREPS(ID) ON UPDATE CASCADE ON DELETE CASCADE
) CHARACTER SET latin1;