CREATE TABLE TOUR_NETWORKS (
 ID               INTEGER UNSIGNED NOT NULL,
 NETWORK          TINYINT UNSIGNED NOT NULL,
 PRIMARY KEY (ID, NETWORK),
 FOREIGN KEY (ID) REFERENCES TOURS(ID) ON UPDATE CASCADE ON DELETE CASCADE
) CHARACTER SET latin1;