CREATE TABLE TOUR_LEGS (
 ID                 INTEGER UNSIGNED NOT NULL,
 IDX                SMALLINT UNSIGNED NOT NULL,
 AIRLINE            CHAR(3) NOT NULL,
 FLIGHT             SMALLINT UNSIGNED NOT NULL,
 LEG                SMALLINT UNSIGNED NOT NULL,
 AIRPORT_D          CHAR(3) NOT NULL,
 AIRPORT_A          CHAR(4) NOT NULL,
 EQTYPE             VARCHAR(15) NOT NULL,
 TIME_D             TIME NOT NULL,
 TIME_A             TIME NOT NULL,
 FLIGHT_TIME        SMALLINT UNSIGNED NOT NULL,
 PRIMARY KEY (ID, IDX),
 FOREIGN KEY (ID) REFERENCES TOURS(ID) ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY (AIRLINE) REFERENCES common.AIRLINES(CODE) ON UPDATE CASCADE,
 FOREIGN KEY (AIRPORT_D) REFERENCES common.AIRPORTS(IATA) ON UPDATE CASCADE,
 FOREIGN KEY (AIRPORT_A) REFERENCES common.AIRPORTS(IATA) ON UPDATE CASCADE,
 FOREIGN KEY (EQTYPE) REFERENCES common.AIRCRAFT(NAME) ON UPDATE CASCADE
) CHARACTER SET latin1;