CREATE TABLE TOURS (
 ID                  INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 NAME                VARCHAR(48) CHARACTER SET utf8mb4 NOT NULL,
 START_DATE          DATETIME NOT NULL,
 END_DATE            DATETIME NOT NULL,
 ACTIVE              BOOLEAN NOT NULL DEFAULT FALSE,
 ACARS_ONLY          BOOLEAN NOT NULL DEFAULT FALSE,
 ALLOW_OFFLINE       BOOLEAN NOT NULL DEFAULT TRUE,
 MATCH_EQ            BOOLEAN NOT NULL DEFAULT FALSE,
 MATCH_LEG           BOOLEAN NOT NULL DEFAULT FALSE,
 PRIMARY KEY (ID)
) CHARACTER SET latin1;