CREATE TABLE ASSIGNMENTS (
 ID						INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 STATUS					SMALLINT,
 PILOT_ID				INTEGER UNSIGNED NOT NULL,
 EVENT_ID				INTEGER UNSIGNED,
 EQTYPE					VARCHAR(15) NOT NULL,
 ASSIGNED_ON			DATE,
 COMPLETED_ON			DATE,
 REPEATS				BOOL,
 RANDOM					BOOL,
 PURGEABLE				BOOL,
 LEGACY_ID				VARCHAR(48),
 PRIMARY KEY (ID)
);

CREATE INDEX FA_ST_IDX ON ASSIGNMENTS(STATUS);
CREATE INDEX FA_PL_IDX ON ASSIGNMENTS(PILOT_ID);
