CREATE TABLE OCEANIC_ROUTES (
 ROUTETYPE              SMALLINT UNSIGNED NOT NULL,
 VALID_DATE             DATE NOT NULL,
 TRACK					CHAR(1) NOT NULL,
 SEQ					SMALLINT UNSIGNED NOT NULL,
 WAYPOINT				VARCHAR(8) NOT NULL,
 LATITUDE				FLOAT(10) NOT NULL,
 LONGITUDE				FLOAT(10) NOT NULL,
 PRIMARY KEY (ROUTETYPE, VALID_DATE, TRACK, SEQ),
 FOREIGN KEY (ROUTETYPE, VALID_DATE) REFERENCES OCEANIC(ROUTETYPE, VALID_DATE) ON DELETE CASCADE
);
