CREATE TABLE CHARTS (
 ID					INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 ICAO				CHAR(4) NOT NULL,
 TYPE				TINYINT UNSIGNED NOT NULL,
 IMGFORMAT	TINYINT UNSIGNED NOT NULL,
 NAME				VARCHAR(48) NOT NULL,
 SIZE					INTEGER UNSIGNED NOT NULL,
 HASH				CHAR(32) NOT NULL,
 UNIQUE (ICAO, NAME),
 PRIMARY KEY (ID),
 FOREIGN KEY (ICAO) REFERENCES AIRPORTS(ICAO) ON UPDATE CASCADE
);
