CREATE TABLE ROUTE_CACHE (
 AIRPORT_D					CHAR(4) NOT NULL,
 AIRPORT_A					CHAR(4) NOT NULL,
 CREATED					DATETIME NOT NULL,
 ALTITUDE					VARCHAR(5) NOT NULL,
 SOURCE						VARCHAR(32) NOT NULL,
 COMMENTS					VARCHAR(255),
 ROUTE						TEXT NOT NULL
);

CREATE INDEX RTCACHE_AP_IDX ON ROUTE_CACHE(AIRPORT_D, AIRPORT_A);
