CREATE TABLE FIR (
 ID			CHAR(4) NOT NULL,
 OCEANIC	BOOLEAN NOT NULL DEFAULT FALSE,
 NAME		VARCHAR(48) NOT NULL,
 DATA       POLYGON NOT NULL SRID 4326,
 PRIMARY KEY (ID, OCEANIC)
);

CREATE SPATIAL INDEX FIR_GEO_IDX ON FIR(DATA);
