CREATE TABLE CHARTURLS (
 ID					INTEGER UNSIGNED NOT NULL,
 SOURCE				VARCHAR(32) NOT NULL,
 URL				VARCHAR(255) NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES CHARTS(ID) ON UPDATE CASCADE ON DELETE CASCADE
);