CREATE TABLE SID_STAR (
 ICAO					CHAR(4) NOT NULL,
 TYPE					TINYINT UNSIGNED NOT NULL,
 NAME					VARCHAR(16) NOT NULL,
 TRANSITION				VARCHAR(8) NOT NULL,
 RUNWAY					VARCHAR(8) NOT NULL,
 SEQ					TINYINT UNSIGNED NOT NULL,
 WAYPOINT				VARCHAR(8) NOT NULL,
 WPTYPE					TINYINT UNSIGNED NOT NULL DEFAULT 3,
 LATITUDE				DECIMAL (10,6) NOT NULL,
 LONGITUDE				DECIMAL (10,6) NOT NULL,
 REGION					VARCHAR(3),
 CAN_PURGE				BOOLEAN NOT NULL DEFAULT 1,
 PRIMARY KEY (ICAO, TYPE, NAME, TRANSITION, RUNWAY, SEQ),
 FOREIGN KEY (ICAO) REFERENCES NAVDATA(CODE) ON UPDATE CASCADE ON DELETE CASCADE,
 CONSTRAINT SID_STAR_WP UNIQUE INDEX (ICAO, TYPE, NAME, TRANSITION, RUNWAY, WAYPOINT)
);

CREATE INDEX SID_NAME_IDX ON SID_STAR(NAME);
