CREATE TABLE SIDSTAR_META (
 ICAO                   CHAR(4) NOT NULL,
 NAME                   VARCHAR(16) NOT NULL,
 TRANSITION             VARCHAR(8) NOT NULL,
 RUNWAY                 VARCHAR(8) NOT NULL,
 TYPE                   TINYINT UNSIGNED NOT NULL,
 ID                     SMALLINT UNSIGNED NOT NULL,
 CAN_PURGE              BOOLEAN NOT NULL DEFAULT TRUE,
 PRIMARY KEY (ICAO, NAME, TRANSITION, RUNWAY),
 FOREIGN KEY (ICAO) REFERENCES NAVDATA(CODE) ON UPDATE CASCADE ON DELETE CASCADE,
 CONSTRAINT SID_STAR_ID UNIQUE INDEX (ICAO, TYPE, ID)
);

CREATE INDEX SID_NAME_IDX ON SIDSTAR_META(NAME);
