CREATE TABLE AIRWAYS (
 NAME					VARCHAR(8) NOT NULL,
 ID						TINYINT UNSIGNED NOT NULL,
 SEQ					TINYINT UNSIGNED NOT NULL,
 WAYPOINT				VARCHAR(8) NOT NULL,
 WPTYPE					TINYINT UNSIGNED NOT NULL DEFAULT 3,
 LATITUDE				DECIMAL (10,6) NOT NULL,
 LONGITUDE				DECIMAL (10,6) NOT NULL,
 FREQ                   VARCHAR(8),
 REGION					VARCHAR(3),
 HIGH					BOOLEAN NOT NULL DEFAULT FALSE,
 LOW					BOOLEAN NOT NULL DEFAULT FALSE,
 LL						POINT NOT NULL SRID 4326,
 PRIMARY KEY (NAME, ID, SEQ)
);