CREATE TABLE GATE_AIRLINES (
 ICAO				CHAR(4) NOT NULL,
 NAME				VARCHAR(16) NOT NULL,
 AIRLINE            CHAR(3) NOT NULL,
 INTL               BOOLEAN NOT NULL DEFAULT FALSE,
 PRIMARY KEY (ICAO, NAME, AIRLINE),
 FOREIGN KEY (ICAO, NAME) REFERENCES common.GATES(ICAO, NAME) ON DELETE CASCADE,
 FOREIGN KEY (AIRLINE) REFERENCES common.AIRLINES(CODE) ON DELETE CASCADE ON UPDATE CASCADE
);