CREATE TABLE NAVDATA (
 ITEMTYPE			TINYINT UNSIGNED NOT NULL,
 CODE				VARCHAR(8) NOT NULL,
 LATITUDE			DECIMAL (10,6) NOT NULL,
 LONGITUDE			DECIMAL (10,6) NOT NULL,
 FREQ				VARCHAR(8),
 ALTITUDE			INTEGER,
 NAME				VARCHAR(48),
 HDG				INTEGER UNSIGNED,
 REGION				VARCHAR(3),
 PRIMARY KEY (CODE, ITEMTYPE, LATITUDE, LONGITUDE, NAME)
);
