CREATE TABLE FIRDATA (
 ID				CHAR(4) NOT NULL,
 OCEANIC		BOOLEAN NOT NULL DEFAULT FALSE,
 SEQ			SMALLINT UNSIGNED NOT NULL,
 LAT			DECIMAL (7,3) NOT NULL,
 LNG			DECIMAL (7,3) NOT NULL,
 PRIMARY KEY (ID, OCEANIC, SEQ),
 FOREIGN KEY (ID, OCEANIC) REFERENCES FIR(ID, OCEANIC) ON DELETE CASCADE ON UPDATE CASCADE
);