CREATE TABLE FIRALIAS (
 ID				CHAR(4) NOT NULL,
 OCEANIC		BOOLEAN NOT NULL DEFAULT FALSE,
 ALIAS			VARCHAR(7) NOT NULL,
 PRIMARY KEY (ID, OCEANIC, ALIAS),
 FOREIGN KEY (ID, OCEANIC) REFERENCES FIR(ID, OCEANIC) ON DELETE CASCADE ON UPDATE CASCADE
);