CREATE TABLE RUNWAYS (
 ICAO				CHAR(4) NOT NULL,
 NAME				VARCHAR(4) NOT NULL,
 SIMVERSION			SMALLINT UNSIGNED NOT NULL,
 LATITUDE			DECIMAL (10,6) NOT NULL,
 LONGITUDE			DECIMAL (10,6) NOT NULL,
 HDG				INTEGER UNSIGNED NOT NULL,
 LENGTH				INTEGER UNSIGNED NOT NULL,
 PRIMARY KEY (ICAO, NAME, SIMVERSION)
);