#!/bin/bash
# Configuration backup script
# (c) 2005, 2006, 2007, 2010, 2011, 2012, 2021 Global Virtual Airlines Group. All Rights Reserved.

# Goto backup directory
cd /home/backup/cfg

# Copy configuration files
tar vcfz authlib.tar.gz /etc/authlib
tar vcfz spamassassin.tar.gz /etc/mail/spamassassin
tar vcfz httpd.tar.gz /usr/local/apache24/conf
tar vcfz postfix.tar.gz /etc/postfix
tar vcfz imapd.tar.gz /etc/dovecot
tar vcfz mysql.tar.gz /etc/my.cnf

# Update permissions
chmod 660 *.tar.gz
chown backup:gva *.tar.gz

# Copy data directories
cd /home/www/gvagroup.org
tar vcfz /home/backup/sites/www.gvagroup.org.tar.gz *

# Update permissions
cd /home/backup/sites
chmod 660 *.tar.gz
chown backup:gva *.tar.gz
exit 0
