#!/bin/sh
# IMAP Mailbox directory creation script
# (c) 2005, 2008 Global Virtual Airlines Group. All Rights Reserved.

# This script merely calls mb_create as root since www cannot write to the directory
sudo mb_create $1 $2
