#!/bin/bash
# SCP database backup script
# Copyright 2007, 2008, 2009, 2011, 2012, 2015, 2024 Global Virtual Airlines Group. All Rights Reserved.
#
# To get automated SSH working, create an SSH key for the user and then copy id_rsa.pub to the
# remote user's home directory ~/.ssh/authorized_keys
#

USER="dva"
if [ "$2" != "" ]; then
        USER="$2"
fi

OPTS="-avr --delete --progress --preallocate --bwlimit=20480"

# Back up base files
cd /home/backup
rsync $OPTS cfg/*.tar.gz $USER@$1:cfg 
rsync $OPTS db/*.bz2 $USER@$1:db
rsync $OPTS sites/*.tar.gz $USER@$1:sites
rsync $OPTS archive/* $USER@$1:archive

# Backup logs via rsync
rsync $OPTS httplogs/* $USER@$1:httplogs
rsync $OPTS --exclude=svn.revision_base svn $USER@$1:

# Backup mail
rsync $OPTS mail/* $USER@$1:mail

# Backup library
rsync $OPTS library/* $USER@$1:library

# Exit with success
exit 0
