#!/bin/bash
# Spam auto-learn script
# (c) 2009, 2012, 2015, 2021 Global Virtual Airlines Group. All Rights Reserved.
#

mail_root='/home/mail'
spam_folder='.!SPAM'
spamd_db='/var/spool/spampd'

for maildir in `ls -AD1 $mail_root`
do
	if [ ! -d $mail_root/$maildir/$spam_folder ]
	then
    	echo 'Creating' $mail_root/$maildir/$spam_folder
		mkdir $mail_root/$maildir/$spam_folder
		mkdir $mail_root/$maildir/$spam_folder/cur
		mkdir $mail_root/$maildir/$spam_folder/new
		mkdir $mail_root/$maildir/$spam_folder/tmp
		chown -R postfix:postfix $mail_root/$maildir/$spam_folder
	else
		if [ `ls -l $mail_root/$maildir/$spam_folder/cur/ | wc -l` -gt "1" ]
		then
			echo 'Checking' $maildir'/cur'
			sa-learn --no-sync --spam --dbpath $spamd_db $mail_root/$maildir/$spam_folder/cur
			rm $mail_root/$maildir/$spam_folder/cur/*
		fi
		if [ `ls -l $mail_root/$maildir/$spam_folder/new/ | wc -l` -gt "1" ]
		then
			echo 'Checking' $maildir'/new'
			sa-learn --no-sync --spam --dbpath $spamd_db $mail_root/$maildir/$spam_folder/new
			rm $mail_root/$maildir/$spam_folder/new/*
		fi
	fi

	# Search for ham
	OIFS="$IFS"
	IFS=$'\n'
	folders=`ls -Ap $mail_root/$maildir | egrep "^\.[A-Z,a-z].*/$" | grep -i delta`
	for fld in $folders
	do
		ffld=`realpath -s $mail_root/$maildir/$fld`
		if [ `ls -l $ffld/new/ | wc -l` -gt "1" ]
		then
			echo 'Processing' $ffld'/new'
			sa-learn --no-sync --ham --dbpath $spamdb $ffld/new
		fi
	done

	IFS=$OIFS
done

# Resync the spamd database
sa-learn --sync --force-expire --dbpath $spamd_db

# Ensure permissions are correct
chown postfix:postfix $spamd_db/*
chmod 660 $spamd_db/*
exit 0
