CREATE TABLE alias (
 address			VARCHAR(255) NOT NULL,
 goto				VARCHAR(255) NOT NULL,
 domain				VARCHAR(255) NOT NULL DEFAULT '',
 created			DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
 modified			DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
 active				BOOL DEFAULT 1,
 PRIMARY KEY (address),
 FOREIGN KEY (goto) REFERENCES mailbox(username) ON DELETE CASCADE ON UPDATE CASCADE
);