CREATE TABLE mailbox (
 username			VARCHAR(255) NOT NULL DEFAULT '',
 password			VARCHAR(96) NOT NULL DEFAULT '',
 name				VARCHAR(255) NOT NULL DEFAULT '',
 maildir			VARCHAR(255) NOT NULL DEFAULT '',
 quota				INTEGER UNSIGNED NOT NULL DEFAULT 0,
 domain				VARCHAR(255) NOT NULL DEFAULT '',
 created			DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
 modified			DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
 active				BOOL DEFAULT 1,
 ID					INTEGER UNSIGNED NOT NULL,
 PRIMARY KEY (username),
 FOREIGN KEY (ID) REFERENCES common.USERDATA(ID)
);