CREATE TABLE GALLERY (
 ID             INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 PILOT_ID       INTEGER UNSIGNED NOT NULL,
 NAME           VARCHAR(192) NOT NULL,
 DATE			DATE NOT NULL,
 DESCRIPTION	TEXT,
 FLEET			BOOLEAN NOT NULL DEFAULT FALSE,
 TYPE           SMALLINT UNSIGNED,
 X              SMALLINT UNSIGNED NOT NULL,
 Y              SMALLINT UNSIGNED NOT NULL,
 SIZE           INTEGER UNSIGNED NOT NULL,
 IMG            MEDIUMBLOB NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (PILOT_ID) REFERENCES PILOTS(ID)
);

CREATE INDEX IMG_NAME ON GALLERY(NAME);
CREATE INDEX IMG_DATE ON GALLERY(DATE);
