CREATE TABLE HELPDESK_FILES (
 ID                         INTEGER UNSIGNED NOT NULL,
 CREATED_ON                 DATETIME NOT NULL,
 SIZE                       INTEGER UNSIGNED NOT NULL DEFAULT 0,
 NAME                       VARCHAR(64) NOT NULL,
 BODY                       MEDIUMBLOB NOT NULL,
 PRIMARY KEY (ID, CREATED_ON),
 FOREIGN KEY (ID, CREATED_ON) REFERENCES HELPDESK_COMMENTS(ID,CREATED_ON) ON DELETE CASCADE
) CHARACTER SET latin1 ENGINE=InnoDB ROW_FORMAT=DYNAMIC;