CREATE TABLE HELPDESK_COMMENTS (
 ID						INTEGER UNSIGNED NOT NULL,
 AUTHOR					INTEGER UNSIGNED NOT NULL,
 CREATED_ON				DATETIME NOT NULL,
 ISFAQ					BOOLEAN DEFAULT 0,
 BODY					TEXT CHARACTER SET utf8 NOT NULL,
 PRIMARY KEY (ID, CREATED_ON),
 FOREIGN KEY (ID) REFERENCES HELPDESK(ID) ON DELETE CASCADE,
 FOREIGN KEY (AUTHOR) REFERENCES common.USERDATA(ID)
);