CREATE TABLE HELPDESK (
 ID						INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 AUTHOR					INTEGER UNSIGNED NOT NULL,
 ASSIGNEDTO				INTEGER UNSIGNED NOT NULL,
 CREATED_ON				DATETIME NOT NULL,
 RESOLVED_ON			DATETIME,
 STATUS					TINYINT UNSIGNED,
 ISPUBLIC				BOOLEAN DEFAULT 0,
 ISFAQ					BOOLEAN DEFAULT 0,
 SUBJECT				VARCHAR(128) NOT NULL,
 BODY					TEXT NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (AUTHOR) REFERENCES common.USERDATA(ID),
 FOREIGN KEY (ASSIGNEDTO) REFERENCES common.USERDATA(ID)
);