CREATE TABLE HELPDESK_LINKS (
 ID                   INTEGER UNSIGNED NOT NULL,
 ISSUE_ID             INTEGER UNSIGNED NOT NULL,
 PRIMARY KEY (ID, ISSUE_ID),
 FOREIGN KEY (ID) REFERENCES HELPDESK(ID) ON DELETE CASCADE,
 FOREIGN KEY (ISSUE_ID) REFERENCES common.ISSUES(ID) ON DELETE CASCADE
);