CREATE TABLE NOTAMS (
 ID					INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 PILOT_ID			INTEGER UNSIGNED NOT NULL,
 EFFDATE			DATE NOT NULL, 
 SUBJECT			VARCHAR(144) NOT NULL,
 BODY				TEXT CHARACTER SET utf8 NOT NULL,
 ACTIVE				BOOLEAN NOT NULL DEFAULT TRUE,
 ISHTML				BOOLEAN NOT NULL DEFAULT FALSE,
 PRIMARY KEY (ID),
 FOREIGN KEY (PILOT_ID) REFERENCES PILOTS(ID)
) ROW_FORMAT=Dynamic;

CREATE INDEX NOTAM_DATE_IDX ON NOTAMS(EFFDATE);