CREATE TABLE NEWS_IMGS (
 ID                 INTEGER UNSIGNED NOT NULL,
 IMG                MEDIUMBLOB NOT NULL,
 X                  SMALLINT UNSIGNED NOT NULL,
 Y                  SMALLINT UNSIGNED NOT NULL,
 TYPE               TINYINT UNSIGNED NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES NEWS(ID) ON DELETE CASCADE
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC;