CREATE TABLE BLOCKS6 (
 ID					INTEGER UNSIGNED NOT NULL,
 BLOCK_START		VARBINARY(16) NOT NULL,
 BLOCK_END			VARBINARY(16) NOT NULL,
 BITS				SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 COUNTRY			CHAR(2) NOT NULL,
 LAT				DECIMAL(7,4) NOT NULL,
 LNG				DECIMAL(7,4) NOT NULL,
 PRIMARY KEY (ID)
) ENGINE=InnoDB;

CREATE INDEX IP6_START ON BLOCKS6(BLOCK_START);
