CREATE TABLE BLOCKS (
 ID					INTEGER UNSIGNED NOT NULL,
 BLOCK_START		VARBINARY(16) NOT NULL,
 BLOCK_END			VARBINARY(16) NOT NULL,
 BITS				SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 LOCATION_ID        INTEGER UNSIGNED NOT NULL,
 LAT				DECIMAL(7,4) NOT NULL,
 LNG				DECIMAL(7,4) NOT NULL,
 RADIUS             SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 PRIMARY KEY (ID)
) ENGINE=InnoDB;

CREATE INDEX IP_START ON BLOCKS(BLOCK_START);