CREATE TABLE BLOCKS6 (
 ID					INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 BLOCK_START		VARBINARY(16) NOT NULL,
 BLOCK_END			VARBINARY(16) NOT NULL,
 COUNTRY			CHAR(2) NOT NULL,
 LAT				DECIMAL(7,4) NOT NULL,
 LNG				DECIMAL(7,4) NOT NULL,
 PRIMARY KEY (ID)
) ENGINE=InnoDB;

CREATE INDEX IP6_START ON BLOCKS6(BLOCK_START);

LOAD DATA INFILE '/tmp/GeoLiteCityv6.csv' INTO TABLE BLOCKS6
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(@ignored, @ignored, @bs, @be, country, @ignored, @ignored, lat, lng, @ignored, @ignored, @ignored)
SET BLOCK_START=CAST(@bs AS DECIMAL(48)), BLOCK_END=CAST(@be AS DECIMAL(48));
