CREATE TABLE LOCATIONS (
  ID				INTEGER UNSIGNED NOT NULL,
  COUNTRY			CHAR(2) NOT NULL,
  REGION			VARCHAR(2) NOT NULL,
  REGION_NAME		VARCHAR(48) NOT NULL,
  CITY				VARCHAR(64) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

LOAD DATA INFILE '/tmp/GeoLiteCity-Location-UTF8.csv' INTO TABLE LOCATIONS
CHARACTER SET utf8 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
IGNORE 2 LINES (id, country, region, city, zip, lat, lng, @ignored, @ignored);
