CREATE TABLE TZ (
 NAME              VARCHAR(64) NOT NULL,
 ID                SMALLINT UNSIGNED NOT NULL DEFAULT 1,
 LAT               DECIMAL(8,4) NOT NULL,
 LNG               DECIMAL(8,4) NOT NULL,
 CTR               POINT NOT NULL SRID 4326,
 DATA              POLYGON NOT NULL SRID 4326,
 PRIMARY KEY (NAME, ID),
 SPATIAL KEY geo_tz(DATA)
) DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;