CREATE TABLE BLOCKS (
  BLOCK_START			INTEGER UNSIGNED NOT NULL,
  BLOCK_END				INTEGER UNSIGNED NOT NULL,
  ID					INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY (BLOCK_START),
  FOREIGN KEY (ID) REFERENCES LOCATIONS(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

LOAD DATA INFILE '/tmp/GeoLiteCity-Blocks.csv' INTO TABLE BLOCKS
CHARACTER SET utf8 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' IGNORE 2 LINES
(block_start, block_end, id);
