CREATE TABLE FIPS_REGIONS (
 COUNTRY		CHAR(2) NOT NULL,
 REGION			VARCHAR(2) NOT NULL,
 NAME			VARCHAR(48) NOT NULL,
 PRIMARY KEY (COUNTRY, REGION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

LOAD DATA INFILE '/tmp/maxmind-region-codes.csv' INTO TABLE FIPS_REGIONS
CHARACTER SET utf8 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(country, region, name);
