CREATE TABLE LOCATIONS (
  ID				INTEGER UNSIGNED NOT NULL,
  COUNTRY			CHAR(2) NOT NULL,
  REGION			VARCHAR(2) NOT NULL,
  CITY				VARCHAR(64) NOT NULL,
  ZIP				VARCHAR(16) NOT NULL,
  LAT				DECIMAL(7,4) NOT NULL,
  LNG				DECIMAL(7,4) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

LOAD DATA INFILE '/tmp/GeoLiteCity-Location-UTF8.csv' INTO TABLE LOCATIONS
CHARACTER SET utf8 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
IGNORE 2 LINES (id, country, region, city, zip, lat, lng, @ignored, @ignored);
