CREATE TABLE COURSEPROGRESS (
 ID						INTEGER UNSIGNED NOT NULL,
 SEQ					INTEGER UNSIGNED NOT NULL,
 AUTHOR					INTEGER UNSIGNED NOT NULL,
 REQENTRY				VARCHAR(255) NOT NULL,
 COMPLETE				BOOL DEFAULT 0,
 COMPLETED				DATETIME,
 PRIMARY KEY (ID, SEQ),
 FOREIGN KEY (ID) REFERENCES COURSES(ID) ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY (ID) REFERENCES common.USERDATA(ID) ON UPDATE CASCADE,
 FOREIGN KEY (AUTHOR) REFERENCES common.USERDATA(ID) ON UPDATE CASCADE
);