CREATE TABLE CERTVIDEOS (
 CERTNAME			VARCHAR(32) NOT NULL,
 FILENAME			VARCHAR(64) NOT NULL,
 PRIMARY KEY (CERTNAME, FILENAME),
 FOREIGN KEY (CERTNAME) REFERENCES CERTS(NAME) ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY (FILENAME) REFERENCES VIDEOS(FILENAME) ON UPDATE CASCADE ON DELETE CASCADE
);