CREATE TABLE CERTROLES (
 CERTNAME			VARCHAR(32) NOT NULL,
 ROLE				VARCHAR(32) NOT NULL,
 PRIMARY KEY (CERTNAME,ROLE),
 FOREIGN KEY (CERTNAME) REFERENCES CERTS(NAME) ON DELETE CASCADE ON UPDATE CASCADE 
);