CREATE TABLE CERTRIDE_SCRIPTS (
 CERTNAME				VARCHAR(32) NOT NULL,
 IDX					SMALLINT UNSIGNED NOT NULL DEFAULT 1,
 SIMS					VARCHAR(32) NOT NULL,
 BODY					TEXT CHARACTER SET utf8mb4 NOT NULL,
 PRIMARY KEY (CERTNAME, IDX),
 FOREIGN KEY (CERTNAME) REFERENCES CERTS(NAME) ON UPDATE CASCADE ON DELETE CASCADE
);
