CREATE TABLE CERTRSRCS (
 ID                  INTEGER UNSIGNED NOT NULL,
 CERT                VARCHAR(8) NOT NULL,
 PRIMARY KEY (ID, CERT),
 FOREIGN KEY (CERT) REFERENCES CERTS(ABBR) ON DELETE CASCADE ON UPDATE CASCADE
) CHARACTER SET latin1;