CREATE TABLE CERTAPPS (
 CERTNAME			VARCHAR(32) NOT NULL,
 AIRLINE			CHAR(3) NOT NULL,
 PRIMARY KEY (CERTNAME, AIRLINE),
 FOREIGN KEY (CERTNAME) REFERENCES CERTS(NAME) ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY (AIRLINE) REFERENCES common.AIRLINEINFO(CODE) ON UPDATE CASCADE
);