CREATE TABLE CERTEXAMS (
 CERTNAME			VARCHAR(32) NOT NULL,
 EXAMNAME			VARCHAR(32) NOT NULL,
 QUESTIONS          SMALLINT NOT NULL,
 PASS_SCORE         SMALLINT,
 TIME               SMALLINT NOT NULL,
 ACTIVE             BOOL,
 PRIMARY KEY (CERTNAME, EXAMNAME),
 FOREIGN KEY (CERTNAME) REFERENCES CERTS(NAME) ON UPDATE CASCADE ON DELETE CASCADE
);