CREATE TABLE COURSEPROGRESS (
 ID						INTEGER UNSIGNED NOT NULL,
 SEQ					INTEGER UNSIGNED NOT NULL,
 REQENTRY				VARCHAR(255) NOT NULL,
 COMPLETE				BOOL DEFAULT 0,
 COMPLETED				DATETIME,
 PRIMARY KEY (ID, SEQ),
 FOREIGN KEY (ID) REFERENCES COURSES(ID) ON UPDATE CASCADE ON DELETE CASCADE
);