CREATE TABLE CERTREQS (
 CERTNAME				VARCHAR(32) NOT NULL,
 SEQ					TINYINT UNSIGNED NOT NULL,
 EXAMNAME				VARCHAR(32),
 REQENTRY				TEXT CHARACTER SET utf8 NOT NULL,
 PRIMARY KEY (CERTNAME, SEQ),
 FOREIGN KEY (CERTNAME) REFERENCES CERTS(NAME) ON UPDATE CASCADE ON DELETE CASCADE
);