CREATE TABLE COURSECHAT (
 COURSE_ID				INTEGER UNSIGNED NOT NULL,
 PILOT_ID				INTEGER UNSIGNED NOT NULL,
 CREATED				DATETIME NOT NULL,
 COMMENTS				TEXT CHARACTER SET utf8mb4 NOT NULL,
 PRIMARY KEY (COURSE_ID, PILOT_ID, CREATED),
 FOREIGN KEY (COURSE_ID) REFERENCES COURSES(ID) ON DELETE CASCADE,
 FOREIGN KEY (PILOT_ID) REFERENCES common.USERDATA(ID) ON DELETE CASCADE
) Row_Format=Dynamic;