CREATE TABLE COURSEPROGRESS (
 ID						INTEGER UNSIGNED NOT NULL,
 SEQ					INTEGER UNSIGNED NOT NULL,
 AUTHOR					INTEGER UNSIGNED NOT NULL,
 REQENTRY				TEXT CHARACTER SET utf8 NOT NULL,
 EXAMNAME				VARCHAR(32),
 COMPLETE				BOOLEAN NOT NULL DEFAULT FALSE,
 COMPLETED				DATETIME,
 PRIMARY KEY (ID, SEQ),
 FOREIGN KEY (ID) REFERENCES COURSES(ID) ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY (AUTHOR) REFERENCES common.USERDATA(ID) ON UPDATE CASCADE
);