CREATE TABLE CERTEQ (
 CERTNAME			VARCHAR(32) NOT NULL,
 EQTYPE				VARCHAR(15) NOT NULL,
 PRIMARY KEY (CERTNAME, EQTYPE),
 FOREIGN KEY (CERTNAME) REFERENCES CERTS(NAME) ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY (EQTYPE) REFERENCES common.AIRCRAFT(NAME) ON UPDATE CASCADE
);