CREATE TABLE INSCALENDAR (
 COURSE				INTEGER UNSIGNED NOT NULL,
 INSTRUCTOR_ID		INTEGER UNSIGNED NOT NULL,
 STARTTIME			DATETIME NOT NULL,
 ENDTIME			DATETIME NOT NULL,
 STATUS				TINYINT UNSIGNED,
 NOSHOW				BOOL DEFAULT 0,
 REMARKS			TEXT,
 PRIMARY KEY (COURSE, INSTRUCTOR_ID, STARTTIME)
 FOREIGN KEY (COURSE) REFERENCES COURSES(ID) ON DELETE CASCADE,
 FOREIGN KEY (INSTRUCTOR_ID) REFERENCES PILOTS(ID) ON DELETE CASCADE
);