CREATE TABLE CERTREQS (
 CERTNAME				VARCHAR(32) NOT NULL,
 REQENTRY				VARHCAR(255) NOT NULL,
 PRIMARY KEY (CERTNAME, REQENTRY),
 FOREIGN KEY CERTNAME REFERENCES CERTS(NAME) ON UPDATE CASCADE ON DELETE CASCADE
);