CREATE TABLE COURSES (
 ID				INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 CERTNAME		VARCHAR(32) NOT NULL,
 PILOT_ID		INTEGER UNSIGNED NOT NULL,
 STATUS			TINYINT UNSIGNED,
 STARTDATE		DATETIME NOT NULL,
 ENDDATE		DATETIME,
 PRIMARY KEY (ID),
 FOREIGN KEY (CERTNAME) REFERENCES CERTS(NAME) ON UPDATE CASCADE,
 FOREIGN KEY (PILOT_ID) REFERENCES PILOTS(ID) ON DELETE CASCADE
);