CREATE TABLE INSCALENDAR (
 ID					INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 COURSE				INTEGER UNSIGNED NOT NULL,
 INSTRUCTOR_ID		INTEGER UNSIGNED NOT NULL,
 STARTTIME			DATETIME NOT NULL,
 ENDTIME			DATETIME NOT NULL,
 STATUS				TINYINT UNSIGNED,
 NOSHOW				BOOLEAN NOT NULL DEFAULT FALSE,
 REMARKS			TEXT CHARACTER SET utf8mb4,
 PRIMARY KEY (ID),
 FOREIGN KEY (COURSE) REFERENCES COURSES(ID) ON DELETE CASCADE,
 FOREIGN KEY (INSTRUCTOR_ID) REFERENCES common.USERDATA(ID) ON DELETE CASCADE
);