CREATE TABLE ACADEMY_ISSUES (
 ID						INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 AUTHOR					INTEGER UNSIGNED NOT NULL,
 CREATED_ON				DATETIME NOT NULL,
 STATUS					TINYINT UNSIGNED,
 SUBJECT				VARCHAR(128) NOT NULL,
 BODY					TEXT NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (AUTHOR) REFERENCES common.USERDATA(ID)
);