CREATE TABLE CERTS (
 NAME				VARCHAR(32) NOT NULL,
 ABBR				VARCHAR(8) NOT NULL,
 STAGE				TINYINT UNSIGNED NOT NULL,
 PREREQ				TINYINT UNSIGNED NOT NULL,
 REQCERT			VARCHAR(8),
 ACTIVE				BOOLEAN NOT NULL DEFAULT FALSE,
 AUTO_ENROLL		BOOLEAN NOT NULL DEFAULT FALSE,
 HAS_CHECKRIDE		BOOLEAN NOT NULL DEFAULT FALSE,
 PRIMARY KEY (NAME)
);