CREATE TABLE CERTS (
 NAME				VARCHAR(32) NOT NULL,
 ABBR				VARCHAR(8) NOT NULL,
 STAGE				TINYINT UNSIGNED NOT NULL,
 PREREQ				TINYINT UNSIGNED NOT NULL,
 REQCERT			VARCHAR(8),
 ACTIVE				BOOLEAN NOT NULL DEFAULT FALSE,
 AUTO_ENROLL		BOOLEAN NOT NULL DEFAULT FALSE,
 VISIBLE            BOOLEAN NOT NULL DEFAULT FALSE,
 CHECKRIDES			TINYINT UNSIGNED NOT NULL DEFAULT 0,
 EQPROGRAM          VARCHAR(15),
 FLIGHTCOUNT        SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 NETWORK            VARCHAR(12),
 RATINGCODE         VARCHAR(5),
 DESCRIPTION		TEXT CHARACTER SET utf8mb4,
 PRIMARY KEY (NAME),
 CONSTRAINT UNIQUE (ABBR)
);