CREATE TABLE COURSERIDES (
 COURSE					INTEGER UNSIGNED NOT NULL,
 CHECKRIDE				INTEGER UNSIGNED NOT NULL,
 PRIMARY KEY (COURSE, CHECKRIDE),
 FOREIGN KEY (COURSE) REFERENCES COURSES(ID) ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY (CHECKRIDE) REFERENCES CHECKRIDES(ID) ON DELETE CASCADE ON UPDATE CASCADE
);