CREATE TABLE ACADEMY_ISSUECOMMENTS (
 ID						INTEGER UNSIGNED NOT NULL,
 AUTHOR					INTEGER UNSIGNED NOT NULL,
 CREATED_ON				DATETIME NOT NULL,
 BODY					TEXT NOT NULL,
 PRIMARY KEY (ID, CREATED_ON),
 FOREIGN KEY (ID) REFERENCES ACADEMY_ISSUES(ID) ON DELETE CASCADE,
 FOREIGN KEY (AUTHOR) REFERENCES common.USERDATA(ID)
);