CREATE TABLE INSLOG (
 ID					INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 INSTRUCTOR_ID		INTEGER UNSIGNED NOT NULL,
 COURSE				INTEGER UNSIGNED NOT NULL,
 EQTYPE				VARCHAR(16) NOT NULL,
 STARTDATE			DATETIME NOT NULL,
 FLIGHT_TIME		NUMERIC(3,1) NOT NULL,
 REMARKS			TEXT,
 PRIMARY KEY (ID),
 FOREIGN KEY (INSTRUCTOR_ID) REFERENCES PILOTS(ID),
 FOREIGN KEY (COURSE) REFERENCES COURSES(ID) ON DELETE CASCADE ON UPDATE CASCADE
);