CREATE TABLE CERTS (
 NAME				VARCHAR(32) NOT NULL,
 ABBR				VARCHAR(8) NOT NULL,
 STAGE				TINYINT UNSIGNED NOT NULL,
 PREREQ				TINYINT UNSIGNED,
 ACTIVE				BOOLEAN DEFAULT 0,
 AUTO_ENROLL		BOOLEAN DEFAULT 0,
 PRIMARY KEY (NAME)
);