CREATE TABLE INSBUSY (
 INSTRUCTOR_ID		INTEGER UNSIGNED NOT NULL,
 STARTTIME			DATETIME NOT NULL,
 ENDTIME			DATETIME NOT NULL,
 COMMENTS			VARCHAR(255),
 PRIMARY KEY (INSTRUCTOR_ID, STARTTIME),
 FOREIGN KEY (INSTRUCTOR_ID) REFERENCES common.USERDATA(ID) ON DELETE CASCADE
);