CREATE TABLE CERTRIDE_SCRIPTS (
 CERTNAME				VARCHAR(32) NOT NULL,
 BODY					TEXT NOT NULL,
 PRIMARY KEY (CERTNAME),
 FOREIGN KEY (CERTNAME) REFERENCES CERTS(NAME) ON UPDATE CASCADE ON DELETE CASCADE
);
