CREATE TABLE COURSES (
 ID				INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 CERTNAME		VARCHAR(32) NOT NULL,
 PILOT_ID		INTEGER UNSIGNED NOT NULL,
 INSTRUCTOR_ID	INTEGER UNSIGNED DEFAULT 0,
 STATUS			TINYINT UNSIGNED,
 STARTDATE		DATETIME NOT NULL,
 ENDDATE		DATETIME,
 CHECKRIDES		TINYINT NOT NULL DEFAULT 0,
 PRIMARY KEY (ID),
 FOREIGN KEY (CERTNAME) REFERENCES CERTS(NAME) ON UPDATE CASCADE,
 FOREIGN KEY (PILOT_ID) REFERENCES common.USERDATA(ID) ON DELETE CASCADE
);

CREATE INDEX COURSE_ST_IDX ON COURSES(STATUS);
