CREATE TABLE CERTDOCS (
 FILENAME			VARCHAR(64) NOT NULL,
 CERTNAME			VARCHAR(32) NOT NULL,
 PRIMARY KEY (FILENAME, CERTNAME),
 FOREIGN KEY (CERTNAME) REFERENCES CERTS(NAME) ON DELETE CASCADE ON UPDATE CASCADE
);