CREATE TABLE CERTPREREQ (
 NAME				VARCHAR(32) NOT NULL,
 ABBR				VARCHAR(8) NOT NULL,
 PRIMARY KEY (NAME),
 FOREIGN KEY (NAME) REFERENCES CERTS(NAME) ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY (ABBR) REFERENCES CERTS(ABBR) ON UPDATE CASCADE
);