CREATE TABLE INSCALENDAR (
 ID					INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 COURSE				INTEGER UNSIGNED NOT NULL,
 INSTRUCTOR_ID		INTEGER UNSIGNED NOT NULL,
 STARTTIME			DATETIME NOT NULL,
 ENDTIME			DATETIME NOT NULL,
 STATUS				TINYINT UNSIGNED,
 NOSHOW				BOOL DEFAULT 0,
 REMARKS			TEXT,
 PRIMARY KEY (ID),
 FOREIGN KEY (COURSE) REFERENCES COURSES(ID) ON DELETE CASCADE,
 FOREIGN KEY (INSTRUCTOR_ID) REFERENCES common.USERDATA(ID) ON DELETE CASCADE
);