CREATE TABLE VIDEOS (
 FILENAME				VARCHAR(64) NOT NULL,
 NAME					VARCHAR(96) NOT NULL,
 CATEGORY				VARCHAR(64) NOT NULL,
 FILESIZE				INTEGER NOT NULL,
 SECURITY				SMALLINT,
 AUTHOR					INTEGER UNSIGNED NOT NULL,
 BODY					TEXT NOT NULL,
 PRIMARY KEY (FILENAME),
 FOREIGN KEY (AUTHOR) REFERENCES common.USERDATA(ID)
);