CREATE TABLE EQAIRLINES (
 EQTYPE					VARCHAR(15) NOT NULL,
 AIRLINE				VARCHAR(3) NOT NULL,
 PRIMARY KEY (EQTYPE, AIRLINE),
 FOREIGN KEY (EQTYPE) REFERENCES EQTYPES(EQTYPE) ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY (AIRLINE) REFERENCES common.AIRLINEINFO(CODE) ON DELETE CASCADE ON UPDATE CASCADE
);