CREATE TABLE EQPROGRAMS (
 EQTYPE					VARCHAR(15) NOT NULL,
 OWNER					CHAR(3) NOT NULL,
 STAGE					SMALLINT UNSIGNED NOT NULL,
 PRIMARY KEY (EQTYPE, OWNER),
 FOREIGN KEY (OWNER) REFERENCES AIRLINEINFO(CODE) ON UPDATE CASCADE 
);
