CREATE TABLE PARTNERS (
 ID             INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 NAME           VARCHAR(48) NOT NULL CHARACTER SET utf8mb4,
 URL            VARCHAR(144) NOT NULL,
 DESCRIPTION    TEXT NOT NULL CHARACTER SET utf8mb4,
 REFERCOUNT     INTEGER UNSIGNED NOT NULL DEFAULT 0,
 PRIMARY KEY (ID)
) CHARACTER SET latin1;

CREATE UNIQUE INDEX PARNTER_NAME ON PARTNERS(NAME);