CREATE TABLE NEWS (
 ID					INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 PILOT_ID			INTEGER UNSIGNED NOT NULL,
 DATE				DATE NOT NULL, 
 SUBJECT			VARCHAR(144) NOT NULL,
 BODY				TEXT CHARACTER SET utf8 NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (PILOT_ID) REFERENCES PILOTS(ID)
);

CREATE INDEX NEWS_DATE_IDX ON NEWS(DATE);
