CREATE TABLE EQTYPES (
 EQTYPE					VARCHAR(15) NOT NULL,
 CP_ID					INTEGER UNSIGNED NOT NULL,
 STAGE					SMALLINT UNSIGNED NOT NULL,
 RANKS					VARCHAR(255) NOT NULL,
 EXAM_FO				VARCHAR(32),
 EXAM_CAPT				VARCHAR(32),
 ACTIVE					BOOLEAN NOT NULL DEFAULT FALSE,
 C_LEGS					SMALLINT,
 C_HOURS				NUMERIC(3,1),
 C_LEGS_ACARS			BOOLEAN NOT NULL DEFAULT FALSE,
 C_LEGS_DISTANCE		SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 C_SWITCH_DISTANCE		SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 C_MIN_1X				SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 C_MAX_ACCEL			SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 PRIMARY KEY (EQTYPE),
 FOREIGN KEY (CP_ID) REFERENCES PILOTS(ID) ON UPDATE CASCADE,
 FOREIGN KEY (EQTYPE) REFERENCES common.AIRCRAFT(NAME) ON UPDATE CASCADE ON DELETE CASCADE
);