CREATE TABLE ACCOMPLISHMENTS (
 ID						INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 NAME					VARCHAR(32) NOT NULL,
 UNIT					TINYINT UNSIGNED NOT NULL,
 VAL					INTEGER UNSIGNED NOT NULL,
 COLOR					INTEGER UNSIGNED NOT NULL DEFAULT 0,
 CHOICES				MEDIUMTEXT,
 ACTIVE					BOOLEAN NOT NULL DEFAULT FALSE,
 PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX ACCOMPLISHMENT_NAME_IDX ON ACCOMPLISHMENTS(NAME);
