CREATE TABLE EQEXAMS (
 EQTYPE					VARCHAR(15) NOT NULL,
 EXAMTYPE				TINYINT UNSIGNED NOT NULL,
 EXAM					VARCHAR(32) NOT NULL,
 PRIMARY KEY (EQTYPE, EXAM, EXAMTYPE),
 FOREIGN KEY (EQTYPE) REFERENCES EQTYPES(EQTYPE) ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY (EXAM) REFERENCES exams.EXAMINFO(NAME) ON DELETE CASCADE ON UPDATE CASCADE
);