CREATE TABLE NOTAMS (
 ID					INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 PILOT_ID			INTEGER UNSIGNED NOT NULL,
 EFFDATE			DATE NOT NULL, 
 SUBJECT			VARCHAR(144) NOT NULL,
 BODY				TEXT CHARACTER SET utf8 NOT NULL,
 ACTIVE				BOOLEAN DEFAULT 0,
 ISHTML				BOOLEAN DEFAULT 0,
 PRIMARY KEY (ID),
 FOREIGN KEY (PILOT_ID) REFERENCES PILOTS(ID)
);

CREATE INDEX NOTAM_DATE_IDX ON NOTAMS(EFFDATE);
