CREATE TABLE NOTAMS (
 ID					INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 PILOT_ID			INTEGER UNSIGNED NOT NULL,
 EFFDATE			DATE NOT NULL, 
 SUBJECT			VARCHAR(144) NOT NULL,
 BODY				TEXT NOT NULL,
 ACTIVE				BOOL DEFAULT 0,
 ISHTML				BOOL DEFAULT 0,
 PRIMARY KEY (ID),
 FOREIGN KEY (PILOT_ID) REFERENCES PILOTS(ID)
);

CREATE INDEX NOTAM_DATE_IDX ON NOTAMS(EFFDATE);
