CREATE TABLE STAFF (
 ID				INTEGER UNSIGNED NOT NULL,
 TITLE			VARCHAR(32) NOT NULL,
 SORT_ORDER		SMALLINT UNSIGNED NOT NULL,
 BIO			TEXT NOT NULL,
 AREA			VARCHAR(32) NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (ID) REFERENCES PILOTS(ID) ON DELETE CASCADE
);
