CREATE TABLE CONTENT_FILTER (
 KEYWORD               VARCHAR(32) CHARACTER SET utf16 NOT NULL,
 UPDATED_ON            DATETIME NOT NULL,
 SAFE                  BOOLEAN NOT NULL DEFAULT FALSE,
 PRIMARY KEY (KEYWORD)
) CHARACTER SET latin1;