CREATE TABLE CONTENT_FILTER (
 KEYWORD               VARCHAR(32) CHARACTER SET utf8mb4 NOT NULL,
 UPDATEDON             DATETIME NOT NULL,
 SAFE                  BOOLEAN NOT NULL DEFAULT FALSE,
 PRIMARY KEY (KEYWORD)
) CHARACTER SET latin1;