CREATE TABLE EQRATINGS (
 EQTYPE					VARCHAR(15) NOT NULL,
 RATING_TYPE			SMALLINT NOT NULL,
 RATED_EQ				VARCHAR(15) NOT NULL,
 PRIMARY KEY (EQTYPE, RATING_TYPE, RATED_EQ),
 FOREIGN KEY (EQTYPE) REFERENCES EQTYPES(EQTYPE) ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY (RATED_EQ) REFERENCES common.AIRCRAFT(NAME) ON UPDATE CASCADE ON DELETE CASCADE
);