CREATE TABLE PARTNERS (
 ID             INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 PRIORITY       SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 NAME           VARCHAR(48) CHARACTER SET utf8mb4 NOT NULL,
 URL            VARCHAR(144) NOT NULL,
 DESCRIPTION    TEXT CHARACTER SET utf8mb4 NOT NULL,
 REFERCOUNT     INTEGER UNSIGNED NOT NULL DEFAULT 0,
 LAST_REFER     DATETIME,
 PRIMARY KEY (ID)
) CHARACTER SET latin1;

CREATE UNIQUE INDEX PARNTER_NAME ON PARTNERS(NAME);