CREATE TABLE EQTYPES (
 EQTYPE					VARCHAR(15) NOT NULL,
 CP_ID					INTEGER UNSIGNED NOT NULL,
 STAGE					SMALLINT NOT NULL,
 RANKS					VARCHAR(255) NOT NULL,
 EXAM_FO				VARCHAR(24),
 EXAM_CAPT				VARCHAR(24),
 ACTIVE					BOOL,
 SO_LEGS				SMALLINT,
 SO_HOURS				NUMERIC(3,1),
 C_LEGS					SMALLINT,
 C_HOURS				NUMERIC(3,1),
 C_LEGS_ACARS			BOOL DEFAULT 0,
 PRIMARY KEY (EQTYPE),
 FOREIGN KEY (CP_ID) REFERENCES PILOTS(ID) ON UPDATE CASCADE
);