CREATE VIEW EQPROGRAMS AS SELECT 'DVA' AS AIRLINE, EQ.EQTYPE, EQ.STAGE,
	GROUP_CONCAT(EA.AIRLINE) AS	AIRLINES FROM dva.EQTYPES EQ, dva.EQAIRLINES EA
	WHERE (EQ.EQTYPE=EA.EQTYPE) GROUP BY EQ.EQTYPE
	UNION SELECT 'AFV', EQ.EQTYPE, EQ.STAGE, GROUP_CONCAT(EA.AIRLINE) from afv.EQTYPES EQ, 
	afv.EQAIRLINES EA WHERE (EQ.EQTYPE=EA.EQTYPE) GROUP BY EQ.EQTYPE ORDER BY AIRLINE, STAGE, EQTYPE;