CREATE TABLE FLIGHTSTATS_NETWORK (
 DATE               DATE NOT NULL,
 NETWORK            TINYINT NOT NULL DEFAULT -1,
 LEGS               INTEGER UNSIGNED NOT NULL DEFAULT 0,
 ACARS              INTEGER UNSIGNED NOT NULL DEFAULT 0,
 HISTORIC           INTEGER UNSIGNED NOT NULL DEFAULT 0,
 DISPATCH           INTEGER UNSIGNED NOT NULL DEFAULT 0,
 SIMBRIEF           INTEGER UNSIGNED NOT NULL DEFAULT 0,
 MILES              INTEGER UNSIGNED NOT NULL DEFAULT 0,
 HOURS              INTEGER UNSIGNED NOT NULL DEFAULT 0,
 PILOTS             NUMERIC(7,1) UNSIGNED NOT NULL DEFAULT 1,
 LOADFACTOR         NUMERIC(5,4) UNSIGNED NOT NULL,
 PAX                INTEGER UNSIGNED NOT NULL DEFAULT 0,
 PRIMARY KEY (DATE, NETWORK)) CHARACTER SET latin1;