CREATE TABLE FLIGHTSTATS_PILOT_DAY (
 DATE               DATE NOT NULL,
 PILOT_ID           INTEGER UNSIGNED NOT NULL,
 PRIMARY KEY (DATE, PILOT_ID),
 FOREIGN KEY (PILOT_ID) REFERENCES PILOTS(ID) ON UPDATE CASCADE ON DELETE CASCADE
);