CREATE TABLE FLIGHTSTATS_LANDSCORE (
 ICAO             CHAR(4) NOT NULL,
 RUNWAY           VARCHAR(3) NOT NULL,
 YEAR             SMALLINT NOT NULL,
 SCORE            INTEGER UNSIGNED NOT NULL,
 SCORE_SD         INTEGER UNSIGNED NOT NULL,
 DISTANCE         SMALLINT NOT NULL,
 DISTANCE_SD      SMALLINT NOT NULL,
 VS               SMALLINT NOT NULL,
 VS_SD            SMALLINT NOT NULL,
 COUNT            SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 PRIMARY KEY (ICAO, RUNWAY, YEAR),
 FOREIGN KEY (ICAO) REFERENCES common.AIRPORTS(ICAO) ON UPDATE CASCADE ON DELETE CASCADE
) CHARACTER SET latin1;
