CREATE TABLE SCHEDULE_HUBS (
 AIRLINE                CHAR(3) NOT NULL,
 AIRPORT                CHAR(3) NOT NULL,
 DESTCOUNT              SMALLINT UNSIGNED NOT NULL DEFAULT 0, 
 PRIMARY KEY (AIRLINE, AIRPORT),
 FOREIGN KEY (AIRLINE) REFERENCES common.AIRLINES(CODE) ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY (AIRPORT) REFERENCES common.AIRPORTS(IATA) ON UPDATE CASCADE ON DELETE CASCADE
) CHARACTER SET latin1;