CREATE TABLE RAW_SCHEDULE (
 AIRLINE            CHAR(3) NOT NULL,
 FLIGHT             SMALLINT UNSIGNED NOT NULL,
 AIRPORT_D          CHAR(3) NOT NULL,
 AIRPORT_A          CHAR(3) NOT NULL,
 EQTYPE             VARCHAR(15) NOT NULL,
 TIME_D             DATETIME NOT NULL,
 TIME_A             DATETIME NOT NULL,
 CS_MASTER          VARCHAR(10),
 PAX_F              SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 PAX_B              SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 PAX_E              SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 PRIMARY KEY (AIRLINE, FLIGHT, TIME_D),
 FOREIGN KEY (AIRLINE) REFERENCES common.AIRLINES(CODE) ON UPDATE CASCADE,
 FOREIGN KEY (AIRPORT_D) REFERENCES common.AIRPORTS(IATA) ON UPDATE CASCADE,
 FOREIGN KEY (AIRPORT_A) REFERENCES common.AIRPORTS(IATA) ON UPDATE CASCADE,
 FOREIGN KEY (EQTYPE) REFERENCES common.AIRCRAFT(NAME) ON UPDATE CASCADE
);