CREATE TABLE RAW_SCHEDULE_AC (
 TAILCODE                  VARCHAR(8) NOT NULL,
 ICAO                      VARCHAR(4) NOT NULL,
 PRIMARY KEY (TAILCODE),
 FOREIGN KEY (ICAO) REFERENCES common.AIRCRAFT(ICAO) ON UPDATE CASCADE
);
