CREATE TABLE RAW_SCHEDULE_AIRLINES (
 SRC                SMALLINT UNSIGNED NOT NULL,
 AIRLINE            CHAR(3) NOT NULL,
 PRIMARY KEY (SRC, AIRLINE),
 FOREIGN KEY (AIRLINE) REFERENCES common.AIRLINES(CODE) ON UPDATE CASCADE
) DEFAULT CHARSET=latin1;