CREATE TABLE RAW_SCHEDULE_DATES (
 SRC                SMALLINT UNSIGNED NOT NULL,
 EFFDATE            DATE NOT NULL,
 IMPORTDATE         DATETIME NOT NULL,
 PRIMARY KEY (SRC)
) DEFAULT CHARSET=latin1;