CREATE TABLE RAW_SCHEDULE_HISTORY (
 SRC                SMALLINT UNSIGNED NOT NULL,
 EFFDATE            DATE NOT NULL,
 IMPORTDATE         DATETIME NOT NULL,
 EXEC_TIME          INTEGER UNSIGNED NOT NULL DEFAULT 0,
 LEGS               INTEGER UNSIGNED NOT NULL DEFAULT 0,
 SKIPPED            INTEGER UNSIGNED NOT NULL DEFAULT 0,
 ADJUSTED           INTEGER UNSIGNED NOT NULL DEFAULT 0,
 PURGED             BOOLEAN NOT NULL DEFAULT FALSE,
 USER_ID            INTEGER UNSIGNED,
 AIRLINES           TEXT NOT NULL,
 PRIMARY KEY (SRC, IMPORTDATE)
) DEFAULT CHARSET=latin1;