CREATE TABLE RAW_SCHEDULE_AC (
 TAILCODE                  VARCHAR(8) NOT NULL,
 EQTYPE                    VARCHAR(15) NOT NULL,
 PRIMARY KEY (TAILCODE),
 FOREIGN KEY (EQTYPE) REFERENCES common.AIRCRAFT(NAME) ON UPDATE CASCADE
);
