CREATE TABLE COUNTRY (
 CODE				CHAR(2) NOT NULL,
 NAME				VARCHAR(64) NOT NULL,
 CONTINENT			VARCHAR(16) NOT NULL,
 DATA               MULTIPOLYGON NOT NULL SRID 4326,
 PRIMARY KEY (CODE)
);

CREATE SPATIAL INDEX CTY_GEO_IDX ON COUNTRY(DATA);