CREATE TABLE APP_AIRLINES (
 CODE				CHAR(3) NOT NULL,
 APPCODE			VARCHAR(3) NOT NULL,
 PRIMARY KEY (CODE, APPCODE),
 FOREIGN KEY (CODE) REFERENCES AIRLINES(CODE) ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY (APPCODE) REFENCES AIRLINEINFO(CODE) ON DELETE CASCADE ON UPDATE CASCADE
);