CREATE TABLE NAVDATA (
 ITEMTYPE			TINYINT UNSIGNED,
 CODE				VARCHAR(8) NOT NULL,
 LATITUDE			FLOAT(10) NOT NULL,
 LONGITUDE			FLOAT(10) NOT NULL,
 FREQ				VARCHAR(8),
 ALTITUDE			INTEGER UNSIGNED,
 NAME				VARCHAR(48),
 HDG				INTEGER UNSIGNED,
 PRIMARY KEY (ITEMTYPE, CODE, FREQ, NAME)
);

CREATE INDEX NAV_CODE_IDX ON NAVDATA(CODE);
CREATE INDEX NAV_TYPE_IDX ON NAVDATA(ITEMTYPE);
