CREATE TABLE AIRLINE_LINKS (
 CODE            CHAR(3) NOT NULL,
 ASSOC           CHAR(3) NOT NULL,
 PRIMARY KEY (CODE, ASSOC),
 FOREIGN KEY (CODE) REFERENCES AIRLINES(CODE) ON UPDATE CASCADE ON DELETE CASCADE,
 FOREIGN KEY (ASSOC) REFERENCES AIRLINES(CODE) ON UPDATE CASCADE ON DELETE CASCADE
) CHARACTER SET latin1;