CREATE TABLE SID_STAR (
 ICAO					CHAR(4) NOT NULL,
 TYPE					TINYINT,
 NAME					VARCHAR(16) NOT NULL,
 TRANSITION				VARCHAR(8) NOT NULL,
 RUNWAY					VARCHAR(8) NOT NULL,
 ROUTE					TEXT NOT NULL,
 PRIMARY KEY (ICAO, NAME, RUNWAY, TRANSITION),
 FOREIGN KEY (ICAO) REFERENCES NAVDATA(CODE) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX SID_NAME_IDX ON SID_STAR(NAME);
