CREATE TABLE CHARTS (
 ID					INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 IATA				CHAR(3) NOT NULL,
 TYPE				SMALLINT NOT NULL,
 NAME				VARCHAR(48) NOT NULL,
 SIZE				INTEGER NOT NULL,
 IMG				MEDIUMBLOB NOT NULL,
 UNIQUE (IATA, NAME),
 PRIMARY KEY (ID),
 FOREIGN KEY (IATA) REFERENCES AIRPORTS(IATA)
);

CREATE INDEX CHART_CN_IDX ON CHARTS(IATA, NAME);