CREATE TABLE AIRLINES (
 CODE				CHAR(3) NOT NULL,
 NAME				VARCHAR(32) NOT NULL,
 ICAO               CHAR(3) NOT NULL,
 COLOR				VARCHAR(12) NOT NULL DEFAULT 'blue';
 ACTIVE				BOOLEAN NOT NULL DEFAULT TRUE,
 SYNC				BOOLEAN NOT NULL DEFAULT FALSE,
 HISTORIC			BOOLEAN NOT NULL DEFAULT FALSE,
 PRIMARY KEY (CODE)
) CHARACTER SET latin1;