CREATE TABLE AIRPORT_AIRLINE (
 CODE					CHAR(3) NOT NULL,
 IATA					CHAR(3) NOT NULL,
 PRIMARY KEY (CODE, IATA),
 FOREIGN KEY (CODE) REFERENCES AIRLINES(CODE) ON DELETE CASCADE,
 FOREIGN KEY (IATA) REFERENCES AIRPORTS(IATA) ON DELETE CASCADE
);