CREATE TABLE SELCAL (
 AIRCRAFT				VARCHAR(8) NOT NULL,
 CODE					CHAR(5) NOT NULL,
 EQTYPE					VARCHAR(16) NOT NULL,
 PILOT_ID				INTEGER UNSIGNED,
 RESERVE_DATE			DATETIME,
 PRIMARY KEY (CODE),
 CONSTRAINT UNIQUE (AIRCRAFT)
);