CREATE TABLE CHARTS (
 ID					INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 IATA				CHAR(3) NOT NULL,
 TYPE				TINYINT UNSIGNED NOT NULL,
 IMGFORMAT			TINYINT UNSIGNED NOT NULL,
 NAME				VARCHAR(48) NOT NULL,
 SIZE				INTEGER UNSIGNED NOT NULL,
 HASH				CHAR(32) NOT NULL,
 IMG				MEDIUMBLOB NOT NULL,
 UNIQUE (IATA, NAME),
 PRIMARY KEY (ID),
 FOREIGN KEY (IATA) REFERENCES AIRPORTS(IATA)
);
