CREATE TABLE AIRWAYS (
 NAME					VARCHAR(8) NOT NULL,
 ID						TINYINT UNSIGNED NOT NULL,
 SEQ					TINYINT UNSIGNED NOT NULL,
 WAYPOINT				VARCHAR(8) NOT NULL,
 WPTYPE					TINYINT UNSIGNED NOT NULL DEFAULT 3,
 LATITUDE				DECIMAL (10,6) NOT NULL,
 LONGITUDE				DECIMAL (10,6) NOT NULL,
 HIGH					BOOLEAN DEFAULT 0,
 LOW					BOOLEAN DEFAULT 0,
 PRIMARY KEY (NAME, ID, SEQ)
);