CREATE TABLE OCEANIC (
 ROUTETYPE              SMALLINT UNSIGNED,
 VALID_DATE             DATE NOT NULL,
 SOURCE                 VARCHAR(96) NOT NULL,
 ROUTE                  TEXT NOT NULL,
 PRIMARY KEY (ROUTETYPE, VALID_DATE)
);