CREATE TABLE ROUTES (
 ID                     INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 AIRPORT_D              CHAR(3) NOT NULL,
 AIRPORT_A              CHAR(3) NOT NULL,
 ARTCC                  VARCHAR(48),
 ROUTE                  VARCHAR(144) NOT NULL,
 PRIMARY KEY (ID),
 FOREIGN KEY (AIRPORT_D) REFERENCES common.AIRPORTS(IATA),
 FOREIGN KEY (AIRPORT_A) REFERENCES common.AIRPORTS(IATA)
);
