CREATE TABLE COUNTRY (
 CODE				CHAR(2) NOT NULL,
 DATA               MULTIPOLYGON NOT NULL SRID 4326,
 PRIMARY KEY (CODE),
 FOREIGN KEY (CODE) REFERENCES COUNTRY(CODE) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE SPATIAL INDEX CTY_GEO_IDX ON COUNTRY(DATA);