CREATE TABLE AIRPORT_AIRLINE (
 CODE					CHAR(3) NOT NULL,
 IATA					CHAR(3) NOT NULL,
 APPCODE				VARCHAR(3) NOT NULL,
 PRIMARY KEY (CODE, IATA, APPCODE),
 FOREIGN KEY (CODE) REFERENCES AIRLINES(CODE) ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY (IATA) REFERENCES AIRPORTS(IATA) ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY (APPCODE) REFERENCES AIRLINEINFO(CODE) ON DELETE CASCADE ON UPDATE CASCADE
);