CREATE TABLE AIRPORTS (
 IATA                   CHAR(3) NOT NULL,
 ICAO                   CHAR(4) NOT NULL,
 TZ						VARCHAR(32) NOT NULL,
 NAME					VARCHAR(48) NOT NULL,
 LATITUDE				FLOAT(10) NOT NULL,
 LONGITUDE				FLOAT(10) NOT NULL,
 ADSE					BOOLEAN NOT NULL DEFAULT FALSE,
 PRIMARY KEY (IATA),
 FOREIGN KEY (TZ) REFERENCES TZ(CODE) ON UPDATE CASCADE
);