CREATE TABLE RAW_SCHEDULE (
 DAY	            TINYINT UNSIGNED NOT NULL DEFAULT 0,
 AIRLINE            CHAR(3) NOT NULL,
 FLIGHT             SMALLINT UNSIGNED NOT NULL,
 LEG                TINYINT UNSIGNED NOT NULL DEFAULT 1,
 AIRPORT_D          CHAR(3) NOT NULL,
 AIRPORT_A          CHAR(3) NOT NULL,
 EQTYPE             VARCHAR(15) NOT NULL,
 TIME_D             DATETIME NOT NULL,
 TIME_A             DATETIME NOT NULL,
 CODESHARE          VARCHAR(10),
 PRIMARY KEY (DAY, AIRLINE, FLIGHT, LEG),
 FOREIGN KEY (AIRLINE) REFERENCES common.AIRLINES(CODE) ON UPDATE CASCADE,
 FOREIGN KEY (AIRPORT_D) REFERENCES common.AIRPORTS(IATA) ON UPDATE CASCADE,
 FOREIGN KEY (AIRPORT_A) REFERENCES common.AIRPORTS(IATA) ON UPDATE CASCADE,
 FOREIGN KEY (EQTYPE) REFERENCES common.AIRCRAFT(NAME) ON UPDATE CASCADE
) DEFAULT CHARSET=latin1;