CREATE TABLE SID_STAR (
 ICAO					CHAR(4) NOT NULL,
 TYPE					TINYINT,
 NAME					VARCHAR(16) NOT NULL,
 TRANSITION				VARCHAR(8) NOT NULL,
 RUNWAY					VARCHAR(8) NOT NULL,
 SEQ					TINYINT UNSIGNED NOT NULL,
 WAYPOINT				VARCHAR(8) NOT NULL,
 LATITUDE				DECIMAL (10,6) NOT NULL,
 LONGITUDE				DECIMAL (10,6) NOT NULL,
 PRIMARY KEY (ICAO, NAME, TRANSITION, RUNWAY, SEQ),
 FOREIGN KEY (ICAO) REFERENCES NAVDATA(CODE) ON UPDATE CASCADE ON DELETE CASCADE,
 CONSTRAINT SID_STAR_WP UNIQUE INDEX (ICAO, NAME, TRANSITION, RUNWAY, WAYPOINT)
);

CREATE INDEX SID_NAME_IDX ON SID_STAR(NAME);
