CREATE TABLE SID_STAR (
 ICAO					CHAR(4) NOT NULL,
 TYPE					TINYINT,
 NAME					VARCHAR(16) NOT NULL,
 TRANSITION				VARCHAR(8) NOT NULL,
 RUNWAY					VARCHAR(8) NOT NULL,
 ROUTE					VARCHAR(192) NOT NULL,
 PRIMARY KEY (ICAO, NAME, TRANSITION),
 FOREIGN KEY (ICAO) REFERENCES AIRPORTS(ICAO) ON UPDATE CASCADE
);