CREATE TABLE NAVDATA (
 ITEMTYPE			TINYINT UNSIGNED,
 CODE				VARCHAR(8) NOT NULL,
 LATITUDE			DECIMAL (10,6) NOT NULL,
 LONGITUDE			DECIMAL (10,6) NOT NULL,
 FREQ				VARCHAR(8),
 ALTITUDE			INTEGER,
 NAME				VARCHAR(48),
 HDG				INTEGER UNSIGNED,
 PRIMARY KEY (ITEMTYPE, CODE, LATITUDE, LONGITUDE, NAME)
);

CREATE INDEX NAV_CODE_IDX ON NAVDATA(CODE);
