CREATE TABLE DSP_SCHEDULE (
 ID						INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
 DISPATCHER				INTEGER UNSIGNED NOT NULL,
 STARTTIME				DATETIME NOT NULL,
 ENDTIME				DATETIME NOT NULL,
 REMARKS				TEXT,
 PRIMARY KEY (ID),
 FOREIGN KEY (DISPATCHER) REFERENCES common.USERDATA(ID) ON UPDATE CASCADE ON DELETE CASCADE
);